### ISSUE TITLE
Integrate V8 Inspector Protocol to debug smart contract

### ISSUE THREAD

**Issue by fbzhong** [nebulasio/go-nebulas#10]
In Nebulas, JavaScript are the first smart contract language by integrating Chrome V8. In V8, there is a V8 Inspector Protocol to help developer develop javascript with Google Chrome browser.

Is anyone interested in helping us integrate V8 Inspector Protocol into Nebulas?

Resources:
https://chromedevtools.github.io/devtools-protocol/
https://github.com/v8/v8/wiki/Debugging-over-the-V8-Inspector-API

**Comment by brandonbevans** [comment]
Hi, I'm aiming to work on this now. Has any work been done on it so far?

**Comment by fbzhong** [comment]
Hi Brandon,

Sorry for late response. The Victor and Simon talked it before, they may have some progress on that.
And, I mentioned you in slack channel.
