### ISSUE TITLE
make bulid error

### ISSUE THREAD

**Issue by XieWeiZM** [nebulasio/go-nebulas#101]
[root@wallet-3 go-nebulas]# make build
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
fatal: Not a git repository (or any of the parent directories): .git
cd cmd/neb; go build -ldflags "-X main.version=0.7.0 -X main.commit= -X main.branch= -X main.compileAt=`date +%s`" -o ../../neb-
# github.com/nebulasio/go-nebulas/storage
../../storage/memory_storage.go:29: undefined: sync.Map
# github.com/nebulasio/go-nebulas/vendor/github.com/libp2p/go-sockaddr/net
../../vendor/github.com/libp2p/go-sockaddr/net/net_linux.go:24: syntax error: unexpected = in type declaration
../../vendor/github.com/libp2p/go-sockaddr/net/net_linux.go:25: syntax error: unexpected = in type declaration
../../vendor/github.com/libp2p/go-sockaddr/net/net_linux.go:26: syntax error: unexpected = in type declaration
../../vendor/github.com/libp2p/go-sockaddr/net/net_linux.go:27: syntax error: unexpected = in type declaration
../../vendor/github.com/libp2p/go-sockaddr/net/net_linux.go:28: syntax error: unexpected = in type declaration
make: *** [build] 错误 2

**Comment by XieWeiZM** [comment]
i  download zip

**Comment by ChengOrangeJu** [comment]
@XieWeiZM What's you golang version?

**Comment by XieWeiZM** [comment]
@ChengOrangeJu  1.9.3

**Comment by ChengOrangeJu** [comment]
@XieWeiZM Yes, I checked the Makefile, it use the git commit version as the neb binary suffix. That's the reason of the starting warning, the other parts seems to be OK
