### ISSUE TITLE
Nebulas 101 - 05 Interacting with Nebulas by RPC API

### ISSUE THREAD

**Issue by xhanthow** [nebulasio/go-nebulas#104]
Example-> RPC-> GetNebState
`conn, err := grpc.Dial(addr, grpc.WithInsecure())`
are right?
the right code is `conn, err := rpc.Dial(addr, grpc.WithInsecure())`?

**Comment by ChengOrangeJu** [comment]
Hello @xhanthow we are looking into the issue, stay tuned:)
