### ISSUE TITLE
TestNet sync block fail!

### ISSUE THREAD

**Issue by maodoutech** [nebulasio/go-nebulas#105]
INFO[2018-05-08T13:46:30+08:00] jcjc save  æµè¯æ¥æ­»å¦111 æ²¡ç¨ç       file=logger.go func=nvm.V8Log line=32
ERRO[2018-05-08T13:46:30+08:00] V8 Exception:
lib/contract.js:53
            _instruction_counter.incr(14);throw new Error("value has been taken");
                                          ^
Error: value has been taken
    at SuperWiki.save (lib/contract.js:53:49)
    at _contract_runner.js:6:29  file=logger.go func=nvm.V8Log line=32
INFO[2018-05-08T13:46:30+08:00] jcjc save  book book                          file=logger.go func=nvm.V8Log line=32
ERRO[2018-05-08T13:46:30+08:00] V8 Exception:
lib/contract.js:67
     _instruction_counter.incr(14);throw new Error("transfer failed.");
                                   ^
Error: transfer failed.
    at BankVaultContract.takeout (lib/contract.js:67:42)
    at _contract_runner.js:6:32  file=logger.go func=nvm.V8Log line=32

INFO[2018-05-08T13:46:31+08:00] jcjc save  ltc litecoin                       file=logger.go func=nvm.V8Log line=32
INFO[2018-05-08T13:46:31+08:00] Succeed to update latest irreversible block.  file=blockchain.go func="core.(*BlockChain).loop" lib.new="{\"height\": 176832, \"hash\": \"c49e2eb7fe42f9b4dcaec172d206e7e51198bfdd9f6c412059d3aaf78575c7e9\", \"parent_hash\": \"ae45bb168794c1a0d0261739f1b31c540244941c42849b7e59a427384080251c\", \"acc_root\": \"f7fd5c3d9aec4697e1587351cd5a1e471345c57ae1b8242191c69d743e1d375a\", \"timestamp\": 1525344645, \"tx\": 0, \"miner\": \"n1dQ7TyMmmoFDqtJYq4RXXUdkkMWKEXpkEd\"}" lib.old="{\"height\": 175427, \"hash\": \"d3d3a9df7ef11f44f5ba2ee2df33fad5cb4c46cbeb21948a490d56ef962b7d36\", \"parent_hash\": \"74b49bd38d4191aafe32ef6bada457db7ffdc257f182267010198755e5cc44c6\", \"acc_root\": \"6a19533e43db65f14f43307d4f1bf0e2c5f2f112727c1f01d26b7f766c43cea9\", \"timestamp\": 1525314615, \"tx\": 0, \"miner\": \"n1ULxbaBLhQmLAa1WQEgHBJCECM12QA7TjH\"}" line=215 miners.limit=15 miners.supported=15 tail="{\"height\": 176857, \"hash\": \"414120ab11c517d155f3ec35db7e75e48a10c9b8512b17c8bf4b9a94bd7d7306\", \"parent_hash\": \"f19393393c888e193b635aedf8fb3863ce55d2899beddb86bde4702c82288554\", \"acc_root\": \"3afea1308c75eeca56c8732f96d0c9df40edba1374b594e49b8c037dd3148205\", \"timestamp\": 1525348080, \"tx\": 0, \"miner\": \"n1cDFK4H2R79LRmVbPXh1nmuBSdDFaCvjNF\"}"
INFO[2018-05-08T13:46:49+08:00] jcjc save  ltc litecoin                       file=logger.go func=nvm.V8Log line=32

INFO[2018-05-08T13:47:19+08:00] jcjc save  ltc litecoin                       file=logger.go func=nvm.V8Log line=32
INFO[2018-05-08T13:47:19+08:00] jcjc save  ltc litecoin                       file=logger.go func=nvm.V8Log line=32
INFO[2018-05-08T13:47:19+08:00] jcjc save  ltc litecoin                       file=logger.go func=nvm.V8Log line=32
INFO[2018-05-08T13:47:19+08:00] jcjc save  ltc litecoin                       file=logger.go func=nvm.V8Log line=32
。。。。。。。。

**Comment by maodoutech** [comment]
print “INFO[2018-05-08T13:47:19+08:00] jcjc save ltc litecoin file=logger.go func=nvm.V8Log line=32”  all the time

**Comment by ChengOrangeJu** [comment]
@maodoutech "jcjc save" maybe some debugging info while verifying history blocks of a smart contract. Testnet is recoverd from upgrading ,try again
