### ISSUE TITLE
先知机

### ISSUE THREAD

**Issue by jianhuaixie** [nebulasio/go-nebulas#106]
question one：Nebulas现在支持先知机吗？比如Oraclize。我想在智能合约里通过先知机获取Web数据。如果这个功能没有的话，所谓的智能合约基本也就只能操作一点点数据而已，并不能打通现有的Web数据。如果未来会支持先知机这一块，能有RoadMap吗？

question two：Nebulas现在支持不同智能合约之间进行数据的访问吗？好像还不能够打通各个智能合约的访问，未来是否支持？Roadmap上有吗？

**Comment by jianhuaixie** [comment]
Nebulas在智能合约里，现在还不能向外面发送http请求吧？

**Comment by ChengOrangeJu** [comment]
@jianhuaixie 非常好的问题，在星云链最新的周报中，已经将不同智能合约之间进行数据的访问列为已完成，很快将在测试网和主网陆续上线。当合约调用的功能发布之后，相信很快会有先知机出现：）敬请期待

**Comment by ChengOrangeJu** [comment]
@jianhuaixie 暂时还没有向外发送http请求的功能

**Comment by haorendashu** [comment]
@ChengOrangeJu 不同智能合约之间互相调用什么时候上线，有没有时间表。

**Comment by ChengOrangeJu** [comment]
@haorendashu I cannot tell that but probably in May

**Comment by m00c0** [comment]
Any updates on this? Is it already deployed on the testnet? Couldn't find a appropriate commit. Would be nice to have some information if possible.

**Comment by ChengOrangeJu** [comment]
@m00c0 updated on mainnet, have a try
