### ISSUE TITLE
Please tell us more about v1.0.2

### ISSUE THREAD

**Issue by green-dalii** [nebulasio/go-nebulas#107]
Could you please show more document details and usage of go-nebulas v1.0.2,such as new `Date` object,`Math.random` object and so on?

**Comment by ChengOrangeJu** [comment]
Hello @green-dalii We will soon update the scope, stay tuned

**Comment by BrushXiaoMinGuo** [comment]
Hi @green-dalii  you can see this document, https://github.com/nebulasio/wiki/blob/master/smart_contract.md. there is usage about `Date` object,`Math.random` object and so on.

**Comment by ChengOrangeJu** [comment]
Thanks @BrushXiaoMinGuo

**Comment by green-dalii** [comment]
@ChengOrangeJu Does 'Date.now()' equals 'Blockchain.block.timestamp'?

**Comment by BrushXiaoMinGuo** [comment]
@green-dalii  Date.now() equals Blockchain.block.timestamp. 
but The Date.now() method returns the number of milliseconds, and Blockchain.block.timestamp is seconds.
