### ISSUE TITLE
Log messages not showing.

### ISSUE THREAD

**Issue by Nufflee** [nebulasio/go-nebulas#108]
It seems like `console.*` messages are not showing anywhere. I'm using the web wallet and they're not showing in the response message nor the browser console. Could use some help on this. And yes, they're in functions that I'm sure are called.

**Comment by Nufflee** [comment]
Solved. I had to run a local node. Now I can see the messages. Thanks, @ChengOrangeJu.

**Comment by ChengOrangeJu** [comment]
Glad to hear that :)
