### ISSUE TITLE
How to build your private chain to mine faster

### ISSUE THREAD

**Issue by ChengOrangeJu** [nebulasio/go-nebulas#109]

**Comment by ChengOrangeJu** [comment]
1. leave only the first dynasty in conf/default/genesis.conf
```
for example:

     dynasty: [
        "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
     ]
```

2. enable start_mine  and set miner & coinbase in conf/default/config.conf
```
diff --git a/conf/default/config.conf b/conf/default/config.conf
index 15b310ce..92f205be 100644
--- a/conf/default/config.conf
+++ b/conf/default/config.conf
@@ -12,7 +12,11 @@ chain {
   datadir: "data.db"
   keydir: "keydir"
   genesis: "conf/default/genesis.conf"
-  start_mine: false
+  start_mine: true
+  miner: "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
+  coinbase: "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
+  passphrase: "passphrase"
   signature_ciphers: ["ECC_SECP256K1"]
 }
```
3. perhaps you need to enable cross domain to make local testing easier
```
rpc {
rpc_listen: ["0.0.0.0:8684"]
http_listen: ["0.0.0.0:8685"]
http_module: ["api","admin"]
# HTTP CORS allowed origins
+ http_cors: ["*"]
}
```

**Comment by hostgame** [comment]
`diff --git a/conf/default/config.conf b/conf/default/config.conf
index 15b310c..755d2ff 100644
--- a/conf/default/config.conf
+++ b/conf/default/config.conf
@@ -12,7 +12,10 @@ chain {
   datadir: "data.db"
   keydir: "keydir"
   genesis: "conf/default/genesis.conf"
-  start_mine: false
+  start_mine: true
+  coinbase: "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
+  miner: "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
+  passphrase: "passphrase"
   signature_ciphers: ["ECC_SECP256K1"]
 }
 
diff --git a/conf/default/genesis.conf b/conf/default/genesis.conf
index ebf8190..323422e 100644
--- a/conf/default/genesis.conf
+++ b/conf/default/genesis.conf
@@ -8,27 +8,7 @@ meta {
 consensus {
   dpos {
     dynasty: [
-      "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE",
-      "n1GmkKH6nBMw4rrjt16RrJ9WcgvKUtAZP1s",
-      "n1H4MYms9F55ehcvygwWE71J8tJC4CRr2so",
-      "n1JAy4X6KKLCNiTd7MWMRsVBjgdVq5WCCpf",
-      "n1LkDi2gGMqPrjYcczUiweyP4RxTB6Go1qS",
-      "n1LmP9K8pFF33fgdgHZonFEMsqZinJ4EUqk",
-      "n1MNXBKm6uJ5d76nJTdRvkPNVq85n6CnXAi",
-      "n1NrMKTYESZRCwPFDLFKiKREzZKaN1nhQvz",
-      "n1NwoSCDFwFL2981k6j9DPooigW33hjAgTa",
-      "n1PfACnkcfJoNm1Pbuz55pQCwueW1BYs83m",
-      "n1Q8mxXp4PtHaXtebhY12BnHEwu4mryEkXH",
-      "n1RYagU8n3JSuV4R7q4Qs5gQJ3pEmrZd6cJ",
-      "n1SAQy3ix1pZj8MPzNeVqpAmu1nCVqb5w8c",
-      "n1SHufJdxt2vRWGKAxwPETYfEq3MCQXnEXE",
-      "n1SSda41zGr9FKF5DJNE2ryY1ToNrndMauN",
-      "n1TmQtaCn3PNpk4f4ycwrBxCZFSVKvwBtzc",
-      "n1UM7z6MqnGyKEPvUpwrfxZpM1eB7UpzmLJ",
-      "n1UnCsJZjQiKyQiPBr7qG27exqCLuWUf1d7",
-      "n1XkoVVjswb5Gek3rRufqjKNpwrDdsnQ7Hq",
-      "n1cYKNHTeVW9v1NQRWuhZZn9ETbqAYozckh",
-      "n1dYu2BXgV3xgUh8LhZu8QDDNr15tz4hVDv"
+      "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
     ]
   }
 }
@@ -37,85 +17,5 @@ token_distribution [
   {
     address: "n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE"
     value: "5000000000000000000000000"
-  },
-  {
-    address: "n1GmkKH6nBMw4rrjt16RrJ9WcgvKUtAZP1s"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1H4MYms9F55ehcvygwWE71J8tJC4CRr2so"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1JAy4X6KKLCNiTd7MWMRsVBjgdVq5WCCpf"
-    value: "5000000000000000000000000"
-  },
-    {
-    address: "n1LkDi2gGMqPrjYcczUiweyP4RxTB6Go1qS"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1LmP9K8pFF33fgdgHZonFEMsqZinJ4EUqk"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1MNXBKm6uJ5d76nJTdRvkPNVq85n6CnXAi"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1NrMKTYESZRCwPFDLFKiKREzZKaN1nhQvz"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1NwoSCDFwFL2981k6j9DPooigW33hjAgTa"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1PfACnkcfJoNm1Pbuz55pQCwueW1BYs83m"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1Q8mxXp4PtHaXtebhY12BnHEwu4mryEkXH"
-    value: "5000000000000000000000000"
-  },
-    {
-    address: "n1RYagU8n3JSuV4R7q4Qs5gQJ3pEmrZd6cJ"
-    value: "5000000000000000000000000"
-  },
-    {
-    address: "n1SAQy3ix1pZj8MPzNeVqpAmu1nCVqb5w8c"
-    value: "5000000000000000000000000"
-  },
-    {
-    address: "n1SHufJdxt2vRWGKAxwPETYfEq3MCQXnEXE"
-    value: "5000000000000000000000000"
-  },
-    {
-    address: "n1SSda41zGr9FKF5DJNE2ryY1ToNrndMauN"
-    value: "5000000000000000000000000"
-  },
-    {
-    address: "n1TmQtaCn3PNpk4f4ycwrBxCZFSVKvwBtzc"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1UM7z6MqnGyKEPvUpwrfxZpM1eB7UpzmLJ"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1UnCsJZjQiKyQiPBr7qG27exqCLuWUf1d7"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1XkoVVjswb5Gek3rRufqjKNpwrDdsnQ7Hq"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1cYKNHTeVW9v1NQRWuhZZn9ETbqAYozckh"
-    value: "5000000000000000000000000"
-  },
-  {
-    address: "n1dYu2BXgV3xgUh8LhZu8QDDNr15tz4hVDv"
-    value: "5000000000000000000000000"
   }
 ]
\ No newline at end of file
diff --git a/docker-compose.yml b/docker-compose.yml
index 15ebbc7..9d21bef 100644
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -17,4 +17,4 @@ services:
     environment:
       - TZ=Asia/Shanghai
       - NEBULAS_BRANCH=master
-    command: bash docker/scripts/neb.bash -c [your conf path]
+    command: bash docker/scripts/neb.bash -c conf/default/config.conf`

**Comment by hostgame** [comment]
Getting this message
```node_1  | time="2018-05-12T18:42:03+08:00" level=fatal msg="Failed to setup blockchain." err="the size of initial dynasty in genesis block is un-safe, should be greater than or equal 15" file=main.go func=main.runNeb line=111```

**Comment by hostgame** [comment]
To fix it you can change DynastySize from 21 to 1 in consensus/dpos/dpos_state.go

**Comment by ChengOrangeJu** [comment]
Thanks @hostgame , I forgot it.

**Comment by jnoodle** [comment]
rm -rf *.db/，之前的测试数据会被删除。

我直接简单粗暴修改了 `core/genesis.go`，注释了273-275行，然后就起来了，交易了几笔，貌似也能正常出块，没仔细看代码，不知道有啥副作用没？

```
		// if len(pGenesis.Consensus.Dpos.Dynasty) != len(pGenesisDB.Consensus.Dpos.Dynasty) {
		//	return ErrGenesisNotEqualDynastyLenInDB
		// }
```

**Comment by catalsdevelop** [comment]
hi, @ChengOrangeJu. I have created a Dockerfile project, which can start a private nebulas network and set mining config in a handy way. you can have try.

**Comment by mirei83** [comment]
I hat to do additional changes in consensus/dpos/dpos_state.go to make it work for me

```
DynastySize              = 1
ConsensusSize            = DynastySize
```

and an `make build` form go-nebulas dir.

Just for all the other noobs like me ;)

**Comment by uranus97s** [comment]
Hi, @ChengOrangeJu. I am having a problem with the node. I did not follow your instructions but it reported an "invalid private key" . Just for all the other noobs like me ;)
```node_1  | time="2019-01-21T09:28:15+08:00" level=error msg="Failed to sign new block" block="{\"height\": 6, \"hash\": \"55c73bc41680e09fa779fb02f5f956ed278a999ff46153b2028c930df6ffc9d5\", \"parent_hash\": \"53740d5082981ce27579450709f51e9db65c65009d1202ed2e1435234406ad29\", \"acc_root\": \"e7f845124e87f43f2543aa784bd6156b4b4d82b129e4e58a176d69eec4219c0f\", \"timestamp\": 1548034095, \"tx\": 0, \"miner\": \"n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE\"}" err="invalid private key" file=dpos.go func="dpos.(*Dpos).mintBlock" line=679 miner=n1FF1nz6tarkDVwWQkMnnwFPuPKUaQTdptE
```
