### ISSUE TITLE
`execution_env.js` not found after pulling the latest commit.

### ISSUE THREAD

**Issue by Nufflee** [nebulasio/go-nebulas#110]
After I pulled the latest changes I got this error: `Error: execution_env.js is not found`.
![image](https://i.imgur.com/aT4k61D.png)
I have no idea where it came from. I have changed some stuff with the dynasty size as @ChengOrangeJu instructed me but I'm pretty sure that didn't cause this issue. From what I can understand, the error is [here](https://github.com/nebulasio/go-nebulas/blob/master/nf/nvm/v8/lib/execution_env.cc#L25). This shouldn't have the `lib/` prefix because it is in the same folder as `execution_env.js`.

**Comment by ChengOrangeJu** [comment]
@Nufflee generally you don't need sudo for starting neb. Perhaps chown you:you the folder and try again without sudo?

**Comment by Arion-Dsh** [comment]
some issue.

**Comment by Nufflee** [comment]
I fixed it by recloning/resetting to head. I'll close this now because it's fixed in my case.
