### ISSUE TITLE
主网api的admin节点已不可用

### ISSUE THREAD

**Issue by Dearkano** [nebulasio/go-nebulas#111]
另外 是否可以提供这种方法：类似本地钱包，接收address&key 对交易进行sign返回data用于raw transaction

**Comment by Dearkano** [comment]
@ChengOrangeJu 后续是否有通过地址和密钥直接发送交易请求的api呢 解锁或者签名比较麻烦

**Comment by ChengOrangeJu** [comment]
@Dearkano 近期没有这个计划，主要出于安全考虑。如果深度经常使用可以考虑用neb.js的api来签名，用脚本还是比较方便的

**Comment by ChengOrangeJu** [comment]
wiki已更新
