### ISSUE TITLE
miner.1.db/LOCK

### ISSUE THREAD

**Issue by happyHou** [nebulasio/go-nebulas#113]
./neb -c conf/example/miner.conf
INFO[2018-05-11T14:36:27+08:00] Setuping Neblet...                            file=neblet.go func="neblet.(*Neblet).Setup" line=111
FATA[2018-05-11T14:36:27+08:00] Failed to open disk storage.                  dir=miner.1.db err="IO error: While lock file: miner.1.db/LOCK: Resource temporarily unavailable" file=main.go func=main.runNeb line=111

**Comment by ChengOrangeJu** [comment]
可以试一下检查后台进程或重启电脑，可能是某资源或端口被占用
