### ISSUE TITLE
Pre-flight (OPTIONS) request fails on testnet & mainnet admin/transactionWithPassphrase.

### ISSUE THREAD

**Issue by Nufflee** [nebulasio/go-nebulas#115]
The request to `https://testnet.nebulas.io/v1/admin/transactionWithPassphrase` (or mainnet equivalent) just redirects to the testnet wiki. Pre-flight requests to other routes do work. Could use some help here. ![](https://i.imgur.com/pvK9b08.png)

**Comment by ChengOrangeJu** [comment]
Hello @Nufflee The admin/xxx endpoint is not supported on mainnet/testnet for safety reasons according to https://github.com/nebulasio/wiki/blob/fe958271f0af3d8f9b43d314fb0fc520e2604984/tutorials/%5BEnglish%5D%20Nebulas%20101%20-%2005%20Interacting%20with%20Nebulas%20by%20RPC%20API.md#modules
