### ISSUE TITLE
Long pendings

### ISSUE THREAD

**Issue by punkkk** [nebulasio/go-nebulas#117]
Hello everyone!

I have very big pendings of transactions. After deploy and launch ./neb it takes ~1-2mins, but after 10+- transactions pending never ends.

Where can be a problem?

**Comment by ChengOrangeJu** [comment]
Hello @punkkk Do you mean you build a private chain with 0 transactions? Or do you start a private node to sync from testnet?

**Comment by punkkk** [comment]
Hi @ChengOrangeJu ty for answer!

I launch default ./neb configs with miner from [this](https://github.com/nebulasio/wiki/blob/master/tutorials/%5BEnglish%5D%20Nebulas%20101%20-%2001%20Installation.md) tutorial. I have deploy little contract and use 'call' and 'transaction' request to call contract's methods, after that i deploy new, bigger contract and deploing transaction just stay with status:2, i've waited more than 30 minutes and it is still in pending.

Sry for bad english.

**Comment by punkkk** [comment]
Oh my god! I just send nonce bigger than actual on 2+...
Account have 0 nonce, i send 5. 

Ty. :)

**Comment by ChengOrangeJu** [comment]
:)
