### ISSUE TITLE
Why is the transaction data max length so small?

### ISSUE THREAD

**Issue by Nufflee** [nebulasio/go-nebulas#118]
The max transaction data length is 128 * 1024 (131072 characters). Why is that? I'm working on an image hosting DApp and that makes it very hard if not even impossible to send very long base64 strings to my contract.

**Comment by ChengOrangeJu** [comment]
Hello @Nufflee For image services, a possible solution is to store the image else where, and the hash on nebulas. I think a possible explanation is that nebulas is not designed for distributed storage

**Comment by Nufflee** [comment]
@ChengOrangeJu  That's possible too but we wanted to go full blockchain so we split the data into multiple transactions and sent it this way.

**Comment by ChengOrangeJu** [comment]
@Nufflee That's a solution 👍
