### ISSUE TITLE
New config schema

### ISSUE THREAD

**Issue by fbzhong** [nebulasio/go-nebulas#12]
Hi,

I'd suggest we change the schema of config.proto in neblet package, which is used config application startup parameters.

The old config schema is less descriptive, fields are not grouped well, and some important fields are missing. 

So I propose to adopt a new config schema, to address the following issues:
 - new **network** config section, describe all basic network configs;
   - neb should support listen on multiple addresses;
 - new **chain** config section, describe chain related configs;
   - chainID, data/key dir, coinbase and gasprice, etc.
 - refined  **rpc** config section;
   - use Enum to describe all available RPC Modules;
   - two types listen address, the one is gPRC, the other is HTTP RESTful;
 - new **app** config section, describe all application's own configs;
   - LogLevel and log dir;
 - new **stats** config section, describe stats/metrics related configs;
 - new **mist** config section, which is no idea to put :)

New config.proto is the following:

```proto
syntax = "proto3";
package nebletpb;

// Neblet global configurations.
message Config {
	// Network config.
    NetworkConfig network  = 1;

	// Chain config.
	ChainConfig chain = 2;

	// RPC config.
	RPCConfig rpc = 3;

	// App Config.
	AppConfig app = 10;

	// Stats config.
	StatsConfig stats = 100;

	// Misc config.
	MiscConfig misc = 101;
}

message NetworkConfig {
	// Neb seed node address.
	repeated string seed = 1;

	// Listen addresses.
	repeated string listen = 2;
}

message ChainConfig {
	// ChainID.
	uint32 chain_id = 1;

	// Data dir.
	string data_dir = 11;

	// Key dir.
	string key_dir = 12;

	// Coinbase.
	string coinbase = 21;

	// GasPrice.
	string gas_price = 22;

	// Supported signature cipher list.
	enum SignatureCiphers {
		ECC_SECP256K1 = 0;
	}
	repeated SignatureCiphers signature_ciphers = 23;
}

message RPCConfig {
	// PRC modules.
	enum RPCModule {
		App = 0;
		Admin = 1;
	}

	// RPC listen addresses.
	repeated string rpc_listen = 1;

	// Enabled RPC modules.
	repeated RPCModule rpc_module = 2;

	// HTTP listen addresses.
	repeated string http_listen = 3;

	// Enabled HTTP modules.
	repeated RPCModule http_module = 4;
}

message AppConfig {
	// LogLevel.
	enum LogLevel {
		Info = 0;
		Warn = 1;
		Error = 2;
		Debug = 3;
	}
	LogLevel log_level = 1;

	// Log dir.
	string log_dir = 2;
}

message MiscConfig {
	// Default encryption ciper when create new keystore file.
    string default_keystore_file_ciper = 1;
}

message StatsConfig {
	// Enable metrics or not.
	bool metrics_enabled = 1;

	// Reporting modules.
	enum ReportingModule {
		Influxdb = 0;
	}
	repeated ReportingModule reporting_module = 2;

	// Influxdb config.
	InfluxdbConfig influxdb = 3;
}

message InfluxdbConfig {
	// Host.
	string host = 1;

	// Port.
	uint32 port = 2;

	// Database name.
	string db = 3;

	// Auth user.
	string user = 4;

	// Auth password.
	string password = 5;
}
```

**Comment by fbzhong** [comment]
Hi guys, 

No any other suggestions or comments? If not, let's impl this new design at this week. @LeonLi000 , you own this feature~

**Comment by LeonLi000** [comment]
I'm working on it now.

**Comment by LeonLi000** [comment]
This c1f52f043a50907f8295dc0cfffcdfa2e47751e0 commit finish this feature.

**Comment by LeonLi000** [comment]
this 4587197ba20baab026d104ab5961c91fb2ab4bc3 commit update this feature.

**Comment by fbzhong** [comment]
@LeonLi000 
Nice works on new config. And I found the ```Enum``` type in config file is **Integer**. For example,
```json
rpc {
    rpc_listen: ["127.0.0.1:51510"]
    http_listen: ["127.0.0.1:8090"]
    http_module: [0,1]
}
```
The ```http_module: [0,1]``` line indicates enabled modules, which is must in range ```API, Admin```.

I don't think the **integer** is more readable than **string**, 0 vs. API.I think we should change the definition, using string directly.

Thanks.

**Comment by LeonLi000** [comment]
Now I have changed the definition, using string directly. The config file looks like this:
```
rpc {
    rpc_listen: ["127.0.0.1:51510"]
    http_listen: ["127.0.0.1:8090"]
    http_module: ["app","admin"]
}
```

**Comment by LeonLi000** [comment]
By the way, I changed the http_module default property 'app' to 'api'.
```
rpc {
    rpc_listen: ["127.0.0.1:51510"]
    http_listen: ["127.0.0.1:8090"]
    http_module: ["api","admin"]
}
```

**Comment by fbzhong** [comment]
cool~
