### ISSUE TITLE
Speed of transactions

### ISSUE THREAD

**Issue by punkkk** [nebulasio/go-nebulas#124]
Hello everyone.

Is it possible to increase speed of transaction on my local net? 

Bcs some of transactions have a lot of time to done.

**Comment by mekery** [comment]
Same question. It takes 315s to mine a new block, even I started 3 miners.

**Comment by m00c0** [comment]
Here is a description of how to achieve your goal.
https://github.com/nebulasio/go-nebulas/issues/109
