### ISSUE TITLE
[Mainnet] : Missing incoming transaction when using Blockchain.transfer

### ISSUE THREAD

**Issue by sarchak** [nebulasio/go-nebulas#128]
### Problem

Here is an example of an address where it has a value that was sent from a Blockchain.transfer but no incoming transactions. As a user, this seems very strange.

[https://explorer.nebulas.io/#/address/n1WP72Tbd8ZiJC7ohxwgtjMZxSW3vEZCTXK](https://explorer.nebulas.io/#/address/n1WP72Tbd8ZiJC7ohxwgtjMZxSW3vEZCTXK)

The Dapp I am building will need to send NAS from smart contract to a bunch of addresses. And without visibility of transaction it is hard for any one to believe the credibility of the smart contract. 

I also think being a ledger it should show each and every transaction `from` and `to` a given address without which the notion of blockchain wouldn't make much sense.
Let me know your thoughts.

**Comment by ChengOrangeJu** [comment]
Hello @sarchak There are events triggered when using Block.transfer which is public to everyone.
However, I agree with you it is a little strange not to show the transaction on explorer. We will have a internal discussion about it, stay tuned :)

**Comment by yupnano** [comment]
Hi sarchak, the explorer will show more information for a transaction that using `Blockchain.transfer`. 
With transaction hash of such a transaction, you can find the details of transfering NAS from contract address to other wallet addresses.

There is still no transaction histories for the wallet addresses receiving NAS from contract. Is the above information sufficient for your Dapp?

**Comment by sarchak** [comment]
@ChengOrangeJu @yupnano thanks for clarification. Yes updating explorer would be a good option for anyone who can verify how the transactions are made.

**Comment by ChengOrangeJu** [comment]
@sarchak After an internal discussion, we plan to support this feature in the explorer in the near future :)
