### ISSUE TITLE
insufficient balance when trying to deploy smart contract

### ISSUE THREAD

**Issue by Gini5** [nebulasio/go-nebulas#129]
Is it possible to deploy smart contract to testnet if balance is 0?
In tutorial it seems possible(https://blog.nebulas.io/2018/04/28/deploy-a-smart-contract/)
But I received 400 error with message 'insufficient balance' when sending request.

**Comment by ChengOrangeJu** [comment]
No, but you can claim nas here https://testnet.nebulas.io/claim/
