### ISSUE TITLE
sync stop at 293846

### ISSUE THREAD

**Issue by bitcodernull** [nebulasio/go-nebulas#130]
block sync stop at 293846, i found the errors:

![image](https://user-images.githubusercontent.com/35094762/40275842-b5cce93e-5c2d-11e8-8eed-c1901ecb9b99.png)

**Comment by ChengOrangeJu** [comment]
Hello @bitcodernull , It could be some sort of timezone inconsistent issue, try to use  
```
TZ='UTC'; export TZ
```
 in your environment and restart the local node
