### ISSUE TITLE
星云链DAPP开发者联盟微信群

### ISSUE THREAD

**Issue by same4869** [nebulasio/go-nebulas#132]
一直没找到一个开发者群，建了一个，欢迎大家加入讨论NAS星云链DAPP开发相关，互相赞应用，讨论创意

![image](https://user-images.githubusercontent.com/5135064/40345300-35b79e20-5dcb-11e8-881a-81ef91b4cac6.png)

**Comment by ChengOrangeJu** [comment]
额，其实官方是有微信群的，请添加官方微信号nebulasio，申请加入技术群

**Comment by 1c7** [comment]
@ChengOrangeJu  官方微信号中午12点左右加了， nebulasio。
现在下午3点暂无回复。不知道是不是再等等就好了。

**Comment by ChengOrangeJu** [comment]
@1c7 微信号还有效，估计稍后即可：）

**Comment by 1c7** [comment]
@ChengOrangeJu ok，感谢回复。
现在5点了，还是暂无回复。我再等等
