### ISSUE TITLE
Math.random.seed 的作用是什么

### ISSUE THREAD

**Issue by yusun** [nebulasio/go-nebulas#133]
我设置了Math.random.seed如下：
var myseed = "1234";
		return Math.random.seed(myseed);
		var result = []
		for(var i=0;i<10;i++){
		result.push(parseInt(Math.random()*100))
		}
		return result;
但发现结果每次调用都不一致。那么提供这个功能的意义在哪里？还有就是test接口中调用Math.random()方法每次获取到的随机数也都不一样。这里是如何保证链上一致性的

**Comment by bibibong** [comment]
@yusun 链上每个块都有一个通过VRF生成的随机种子，同一块内产生的随机数都是可验证的。不同块随机种子不一样，多次调用（包括test）是在不同块上执行的所以随机数不一样，你可以通过Blockchain.block.seed拿到当前种子看看。Math.random.seed()这个方法你可以理解为给随机种子加盐，让随机数有更多变化可能。

**Comment by yusun** [comment]
多次调用极短间隔，理论上是在同一个块上进行随机计算。为什么会返回不一样。是否考虑提供直接作为seed的随机数方法，而不是加盐。 如果提供的话很多区块链上游戏的模拟执行结果就能和最终结果一致。这样应用场景应该更广泛一点

**Comment by bibibong** [comment]
@yusun 
1. test方法是在临时块上执行的所以每次不一样，和链上执行结果没有关系。随机结果如果能通过模拟执行提前知道，相信你也清楚这是存在作弊风险的。
2. seed完全可以认为就是直接设置新的种子，内部怎么实现，加盐与否并没什么区别。

**Comment by bibibong** [comment]
@yusun 你是想要一个可以预测结果随机数方案？从区块链的角度考虑我们是不打算支持这种有潜在作弊风险的方案的。如果有需要，可以在合约内自己集成随机算法实现

**Comment by yusun** [comment]
@bibibong 是否可以考虑提供类似获取历史区块随机数的方法。这样我就能对过去发生的事情获取确定性的结果。但是对未来依然一无所知。如果我集成随机数就有作弊的可能性了

**Comment by bibibong** [comment]
@yusun 获取历史区块信息的方法已经在计划中了
