### ISSUE TITLE
添加一些在 Contract.call 执行的时候可能用到的方法

### ISSUE THREAD

**Issue by haorendashu** [nebulasio/go-nebulas#135]
在这个文件：
https://github.com/nebulasio/go-nebulas/blob/feature/internal_nvm/nf/nvm/v8/lib/blockchain.js
执行 Contract.call 的时候，在目标合约里面，能不能有方法，**知道当前合约的调用是由某个合约发起的、以及知道发起该调用的合约的地址。**

感觉如果有这两个方法，可以更加方便地构造一些复杂的合约系统。

例如：[浅谈以太坊智能合约的设计模式与升级方法](https://github.com/toxotguo/thinking/blob/master/%E6%B5%85%E8%B0%88%E4%BB%A5%E5%A4%AA%E5%9D%8A%E6%99%BA%E8%83%BD%E5%90%88%E7%BA%A6%E7%9A%84%E8%AE%BE%E8%AE%A1%E6%A8%A1%E5%BC%8F%E4%B8%8E%E5%8D%87%E7%BA%A7%E6%96%B9%E6%B3%95.md) 这里面提到的控制器合约和数据合约组合一起工作时，可以指定数据合约只能由哪些控制器合约来调用。

**Comment by ChengOrangeJu** [comment]
hi @haorendashu , we plan to add this feature in the near future, thanks

**Comment by ChengOrangeJu** [comment]
We are looking into this issue, stay tuned :)

**Comment by Silentttttt** [comment]
Blockchain.verifyAddress(Blockchain.transaction.from) will return the address type, 0x57 means that it is a normal address and 0x58 means a contract address.
