### ISSUE TITLE
[疑问] Nebulas 合约可以调用另一个合约吗

### ISSUE THREAD

**Issue by frankwei98** [nebulasio/go-nebulas#137]
假设我有一个 NRC20 Token 合约和一个 Banking 合约，我想Banking 合约访问到NRC20 Token的部分方法。

在以太坊的 Solidity 有 Interface 这个类型可以生成一个合约对象实例来访问合同的方法

**Comment by ChengOrangeJu** [comment]
该功能近期将上线

**Comment by frankwei98** [comment]
18 days later, any update?

**Comment by frankwei98** [comment]
almost a month later, any update? please?

**Comment by haorendashu** [comment]
该功能是不是准备要上 testnet 了？看到分支测试代码已经提交，可是 testnet 上还是没法使用。

**Comment by yupnano** [comment]
@haorendashu 现在已经上线testnet了，欢迎试用。

**Comment by haorendashu** [comment]
@yupnano 你好 我想问问 合约之间调用，能不能在被调用合约上拿到调用合约的地址（不是合约调用者）
