### ISSUE TITLE
Unable to transfer full wallet balance

### ISSUE THREAD

**Issue by smartpunter** [nebulasio/go-nebulas#138]
Steps to reproduce:
1) Get wallet balance in WEI using getAccountState
2) Subsctract standart gas transfer amount 20 000, multiplied by gas price 1 000 000
3) Send remaining amount as value for transaction to send by sendRawTransaction method.
4) Transaction fails.

Even if i substract more (even much more!) it still fails, while occasionnaly being succsefulll. All amounts are integers.

Seems like problems in Nebulas blockchain for me.

**Comment by smartpunter** [comment]
Figured it out.
For succesfull transaction you need to have on purse value of transaction AND gasLimit * gasPrice. Otherwise it will fail. We were sending default gasLimit 200 000... Please clearly state about this in docs.

**Comment by ChengOrangeJu** [comment]
@smartpunter This is a very good question, you dive into the details of go-nebulas. The verification before execute a transaction can be found in transaction.go: func VerifyExecution(). 

May be we should add more detail explanation to a separate wiki or show the code directly.
There could be lots of such details and the best explanation can be found in code…
