### ISSUE TITLE
是否考虑合同内支持RSA加解密？

### ISSUE THREAD

**Issue by TonyXuCoding** [nebulasio/go-nebulas#141]
最近在开发一个扑克牌类的DAPP，需要实现一个需求：玩家（比如2位）加入后自动触发智能合约发牌的逻辑，每个玩家获得一张牌，并且只对自己可见

用户查看自己的牌，客户端一般是通过调用查询类的合同接口实现的，但是这类接口是没有权限验证的，也就是对方（或任何人）可以看到自己的底牌

为了解决这个问题，客户端（WEB）为每个用户另外生成了RSA秘钥对，同时在合同内置了RSA加密模块。每个玩家在加入游戏时（会调用对应的合同接口），需要额外传入RSA公钥。客户端在查询底牌时，返回的结果会用各自的公钥加密，客户端拿到之后再用私钥解密

（这里的RSA公钥和公链账户体系的公钥是完全独立的）

由于合同内是没法引入自定义模块的，而RSA的JS实现一般都有4000行左右，直接拷贝这样的大段代码到合同里，既不优雅，也增加开发者调用DAPP的难度。

最后，解决在公开信道上的加密传输问题（现在可以理解为明文传输），能够开发出更多有趣的博弈类应用。对于这类问题不知道星云链的开发团队怎么考虑的？谢谢~

=======
以上，可能理解有误，欢迎指正~

**Comment by ChengOrangeJu** [comment]
@TonyXuCoding 
1. 权限验证是否可以通过判断transaction.from来实现？类似 https://github.com/nebulasio/wiki/blob/master/permission_control_in_smart_contract.md

2. rsa加密这个我理解可能更合适的一个地方是放在客户端来实现（比如钱包或浏览器插件钱包），用公钥加密+返回后用私钥解密

3. 是的，如果有其他的通用增加js库的需求，我们一定会予以支持，近期sha1,sha256等加密算法会上线

**Comment by ChengOrangeJu** [comment]
https://github.com/nebulasio/web-wallet/issues/50
是一个类似的需求。请问能否满足需求？

**Comment by TonyXuCoding** [comment]
@ChengOrangeJu 
1. 操作类的权限判断可以用这个方法，读取类的应该不行
2. 赞同
3. 这个很赞，DAPP实现的新方案该用sha1了，由于代码段比较短，可以直接放到合同里。期待以后内置这个模块
