### ISSUE TITLE
make build error, cannot find package 

### ISSUE THREAD

**Issue by LiaoPeng** [nebulasio/go-nebulas#142]
macOS High Sierra
go version go1.10.2 darwin/amd64

cd cmd/neb; go build -ldflags "-X main.version=1.0.1 -X main.commit=a7aaa0aaef2677038562356e1bbdccfb848d2fb4 -X main.branch=master -X main.compileAt=date +%s" -o ../../neb-a7aaa0aaef2677038562356e1bbdccfb848d2fb4
../../core/block_pool.go:27:2: cannot find package "github.com/hashicorp/golang-lru" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/hashicorp/golang-lru (from $GOROOT)
/Users/nebulas/go/src/github.com/hashicorp/golang-lru (from $GOPATH)
../../net/route_table.go:38:2: cannot find package "github.com/libp2p/go-libp2p-kbucket" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/libp2p/go-libp2p-kbucket (from $GOROOT)
/Users/nebulas/go/src/github.com/libp2p/go-libp2p-kbucket (from $GOPATH)
../../net/node.go:29:2: cannot find package "github.com/libp2p/go-libp2p-net" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/libp2p/go-libp2p-net (from $GOROOT)
/Users/nebulas/go/src/github.com/libp2p/go-libp2p-net (from $GOPATH)
../../net/node.go:30:2: cannot find package "github.com/libp2p/go-libp2p-peer" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/libp2p/go-libp2p-peer (from $GOROOT)
/Users/nebulas/go/src/github.com/libp2p/go-libp2p-peer (from $GOPATH)
../../net/route_table.go:40:2: cannot find package "github.com/libp2p/go-libp2p-peerstore" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/libp2p/go-libp2p-peerstore (from $GOROOT)
/Users/nebulas/go/src/github.com/libp2p/go-libp2p-peerstore (from $GOPATH)
../../net/node.go:31:2: cannot find package "github.com/libp2p/go-libp2p-swarm" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/libp2p/go-libp2p-swarm (from $GOROOT)
/Users/nebulas/go/src/github.com/libp2p/go-libp2p-swarm (from $GOPATH)
../../net/node.go:32:2: cannot find package "github.com/libp2p/go-libp2p/p2p/host/basic" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/libp2p/go-libp2p/p2p/host/basic (from $GOROOT)
/Users/nebulas/go/src/github.com/libp2p/go-libp2p/p2p/host/basic (from $GOPATH)
../../net/config.go:26:2: cannot find package "github.com/multiformats/go-multiaddr" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/multiformats/go-multiaddr (from $GOROOT)
/Users/nebulas/go/src/github.com/multiformats/go-multiaddr (from $GOPATH)
../../rpc/pb/rpc.pb.gw.go:16:2: cannot find package "github.com/nebulasio/grpc-gateway/runtime" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/nebulasio/grpc-gateway/runtime (from $GOROOT)
/Users/nebulas/go/src/github.com/nebulasio/grpc-gateway/runtime (from $GOPATH)
../../rpc/pb/rpc.pb.gw.go:17:2: cannot find package "github.com/nebulasio/grpc-gateway/utilities" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/nebulasio/grpc-gateway/utilities (from $GOROOT)
/Users/nebulas/go/src/github.com/nebulasio/grpc-gateway/utilities (from $GOPATH)
../console/console.go:34:2: cannot find package "github.com/peterh/liner" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/peterh/liner (from $GOROOT)
/Users/nebulas/go/src/github.com/peterh/liner (from $GOPATH)
../../metrics/influxdb.go:10:2: cannot find package "github.com/rcrowley/go-metrics" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/rcrowley/go-metrics (from $GOROOT)
/Users/nebulas/go/src/github.com/rcrowley/go-metrics (from $GOPATH)
../../metrics/metrics.go:31:2: cannot find package "github.com/rcrowley/go-metrics/exp" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/rcrowley/go-metrics/exp (from $GOROOT)
/Users/nebulas/go/src/github.com/rcrowley/go-metrics/exp (from $GOPATH)
../../util/logging/hooker_filerotate.go:27:2: cannot find package "github.com/rifflock/lfshook" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/rifflock/lfshook (from $GOROOT)
/Users/nebulas/go/src/github.com/rifflock/lfshook (from $GOPATH)
../console/jsbridge.go:32:2: cannot find package "github.com/robertkrimen/otto" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/robertkrimen/otto (from $GOROOT)
/Users/nebulas/go/src/github.com/robertkrimen/otto (from $GOPATH)
../../rpc/gateway.go:12:2: cannot find package "github.com/rs/cors" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/rs/cors (from $GOROOT)
/Users/nebulas/go/src/github.com/rs/cors (from $GOPATH)
../../crypto/cipher/scrypt.go:31:2: cannot find package "github.com/satori/go.uuid" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/satori/go.uuid (from $GOROOT)
/Users/nebulas/go/src/github.com/satori/go.uuid (from $GOPATH)
../../util/logging/hooker_filerotate.go:28:2: cannot find package "github.com/sirupsen/logrus" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/sirupsen/logrus (from $GOROOT)
/Users/nebulas/go/src/github.com/sirupsen/logrus (from $GOPATH)
../../storage/disk_storage.go:26:2: cannot find package "github.com/syndtr/goleveldb/leveldb" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/syndtr/goleveldb/leveldb (from $GOROOT)
/Users/nebulas/go/src/github.com/syndtr/goleveldb/leveldb (from $GOPATH)
../../storage/disk_storage.go:27:2: cannot find package "github.com/syndtr/goleveldb/leveldb/filter" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/syndtr/goleveldb/leveldb/filter (from $GOROOT)
/Users/nebulas/go/src/github.com/syndtr/goleveldb/leveldb/filter (from $GOPATH)
../../storage/disk_storage.go:28:2: cannot find package "github.com/syndtr/goleveldb/leveldb/opt" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOROOT)
/Users/nebulas/go/src/github.com/syndtr/goleveldb/leveldb/opt (from $GOPATH)
../../storage/rocks_storage.go:10:2: cannot find package "github.com/tecbot/gorocksdb" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/tecbot/gorocksdb (from $GOROOT)
/Users/nebulas/go/src/github.com/tecbot/gorocksdb (from $GOPATH)
accountcmd.go:27:2: cannot find package "github.com/urfave/cli" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/urfave/cli (from $GOROOT)
/Users/nebulas/go/src/github.com/urfave/cli (from $GOPATH)
../../net/recved_message.go:27:2: cannot find package "github.com/willf/bloom" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/github.com/willf/bloom (from $GOROOT)
/Users/nebulas/go/src/github.com/willf/bloom (from $GOPATH)
../../crypto/hash/hash.go:25:2: cannot find package "golang.org/x/crypto/ripemd160" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/golang.org/x/crypto/ripemd160 (from $GOROOT)
/Users/nebulas/go/src/golang.org/x/crypto/ripemd160 (from $GOPATH)
../../crypto/cipher/scrypt.go:32:2: cannot find package "golang.org/x/crypto/scrypt" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/golang.org/x/crypto/scrypt (from $GOROOT)
/Users/nebulas/go/src/golang.org/x/crypto/scrypt (from $GOPATH)
../../crypto/hash/hash.go:26:2: cannot find package "golang.org/x/crypto/sha3" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/golang.org/x/crypto/sha3 (from $GOROOT)
/Users/nebulas/go/src/golang.org/x/crypto/sha3 (from $GOPATH)
../../../../grpc-ecosystem/go-grpc-middleware/chain.go:9:2: cannot find package "golang.org/x/net/context" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/golang.org/x/net/context (from $GOROOT)
/Users/nebulas/go/src/golang.org/x/net/context (from $GOPATH)
../../rpc/server.go:8:2: cannot find package "golang.org/x/net/netutil" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/golang.org/x/net/netutil (from $GOROOT)
/Users/nebulas/go/src/golang.org/x/net/netutil (from $GOPATH)
../../rpc/pb/rpc.pb.go:60:8: cannot find package "google.golang.org/genproto/googleapis/api/annotations" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/google.golang.org/genproto/googleapis/api/annotations (from $GOROOT)
/Users/nebulas/go/src/google.golang.org/genproto/googleapis/api/annotations (from $GOPATH)
../../../../grpc-ecosystem/go-grpc-middleware/chain.go:10:2: cannot find package "google.golang.org/grpc" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/google.golang.org/grpc (from $GOROOT)
/Users/nebulas/go/src/google.golang.org/grpc (from $GOPATH)
../../rpc/pb/rpc.pb.gw.go:20:2: cannot find package "google.golang.org/grpc/codes" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/google.golang.org/grpc/codes (from $GOROOT)
/Users/nebulas/go/src/google.golang.org/grpc/codes (from $GOPATH)
../../rpc/pb/rpc.pb.gw.go:21:2: cannot find package "google.golang.org/grpc/grpclog" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/google.golang.org/grpc/grpclog (from $GOROOT)
/Users/nebulas/go/src/google.golang.org/grpc/grpclog (from $GOPATH)
../../rpc/server.go:17:2: cannot find package "google.golang.org/grpc/reflection" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/google.golang.org/grpc/reflection (from $GOROOT)
/Users/nebulas/go/src/google.golang.org/grpc/reflection (from $GOPATH)
../../rpc/pb/rpc.pb.gw.go:22:2: cannot find package "google.golang.org/grpc/status" in any of:
/usr/local/Cellar/go/1.10.2/libexec/src/google.golang.org/grpc/status (from $GOROOT)
/Users/nebulas/go/src/google.golang.org/grpc/status (from $GOPATH)
make: *** [build] Error 1

**Comment by ChengOrangeJu** [comment]
Seems like gopath not setting correctly. Have you solved this issue?

**Comment by LiaoPeng** [comment]
I had download the package through git by hand.
