### ISSUE TITLE
make build error ,clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by LiaoPeng** [nebulasio/go-nebulas#143]
cd cmd/neb; go build -ldflags "-X main.version=1.0.1 -X main.commit=a7aaa0aaef2677038562356e1bbdccfb848d2fb4 -X main.branch=master -X main.compileAt=`date +%s`" -o ../../neb-a7aaa0aaef2677038562356e1bbdccfb848d2fb4
# github.com/nebulasio/go-nebulas/crypto/cipher
../../crypto/cipher/scrypt.go:110:13: multiple-value uuid.NewV4() in single-value context
# github.com/tecbot/gorocksdb
ld: library not found for -lsnappy
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [build] Error 2

**Comment by ChengOrangeJu** [comment]
Does this issue help ? https://github.com/spicavigo/kafka-rust/issues/27
