### ISSUE TITLE
Map storage in contract's error(a['b'] is not same with a.get('b')

### ISSUE THREAD

**Issue by zoowii** [nebulasio/go-nebulas#145]
in nebulas smart contract, assume balances is a map type storage

balances['a'] = 1 is not equal to balances.get('a') in nebulas contract

If I ran `balances['a'] = 1`, then I can get `balances.get('a')` equal to undefined and `balances['a']` equal to 1

**Comment by ChengOrangeJu** [comment]
It should be equal, do you have code example for it ?
