### ISSUE TITLE
测试网络数据同步问题

### ISSUE THREAD

**Issue by zhaoqijiong** [nebulasio/go-nebulas#149]
测试网络同步到401835区块时就同步不下去了, 清掉数据重新同步还是在这个区块过不去
使用的是master分支的代码编译的

这个是什么原因?

![p](https://user-images.githubusercontent.com/1332625/41327400-ea544668-6ef5-11e8-87ac-fd8cc09355f2.png)

**Comment by yupnano** [comment]
你好，方便把log文件发给我们来查找原因吗？我的邮箱是 peng.yu@nebulas.io

发 go-nebulas/logs 目录下的最新的一个log文件就可以。

**Comment by zhaoqijiong** [comment]
邮件已发,请查收

**Comment by yupnano** [comment]
你好，请先使用testnet分支的代码来同步testnet数据吧。

**Comment by zhaoqijiong** [comment]
testnet分支 好像没有新提交代码?
现在编译了还是过不去

日志文件如下:
[neb-20180613-18.log](https://github.com/nebulasio/go-nebulas/files/2097711/neb-20180613-18.log)

**Comment by ChengOrangeJu** [comment]
可以试试目前版本的主网，应该是没有同步问题的：）
