### ISSUE TITLE
主网节点同步失败 

### ISSUE THREAD

**Issue by zhaoqijiong** [nebulasio/go-nebulas#152]
错误日志如下

time="2018-06-17T06:25:30+08:00" level=info msg="Failed to execute payload" block="{\"height\": 446863, \"hash\": \"69d8142e546e052a794ee7b0b3119e610e9c74c5e34bb93c370a5bbe46ded611\", \"parent_hash\": \"87c2725f08a91ddeb8ab05d4f3653dd0dda8e910f753501c423556888d13c390\", \"acc_root\": \"b6e0bbd3ae2d8b93311f0e491f3d53f1be08caa7594e345870d88b7e08e9ff4a\", \"timestamp\": 1529092230, \"tx\": 6, \"miner\": \"n1JEsMkcLW7mQfjGTrLCxw4GU8Bzzf5i1m4\", \"random\": \"/vrf_seed/de9b69f80be5660b8d69f3c826d1eb873f922d0357195ba2a36e46ecdabaa28c/vrf_proof/27710343423c61c602db5c347f659ded09cc5a110fb421f7e849dd0059359053410b2940cea5438c62f922c535a3a89e9e60d78dd662415bb9f8c3f5ad104609042625e6ff4ae99631ecdaaa8041854cfce069bc1299cd031c5be8e7def86fc2d9e6a50d3dd1b76e8644f5407f3eecef75fb696c8f6cceb871d93cc49eff5c495b\"}" err="execution timeout" file=transaction.go func=core.VerifyExecution line=572 transaction="{\"chainID\":1, \"hash\":\"b11b499b4ea7395f69a2f36b4ffd667efd81cc1577631f524f433f08b33dea80\", \"from\":\"n1Vk4pTWvwhKnk6rwGaCwgJdJo6zQf6yJfB\", \"to\":\"n1Vk4pTWvwhKnk6rwGaCwgJdJo6zQf6yJfB\", \"nonce\":143, \"value\":\"0\", \"timestamp\":1529092209, \"gasprice\": \"1000000\", \"gaslimit\":\"20000000\", \"data\": \"{\"SourceType\":\"js\",\"Source\":\"'use strict';\\n\\nconst gridWidth = 200;\\nconst gridHeight = 200;\\nconst priceThresholdWei = new BigNumber(10000000);\\n\\nfunction isValidColor(sNum) {\\n  return (typeof sNum === \\\"string\\\") \\u0026\\u0026 sNum.length === 6\\n    \\u0026\\u0026 !isNaN(parseInt(sNum, 16));\\n}\\n\\nfunction isValidNumber(value, min, max) {\\n  if (typeof value !== 'number') {\\n    return false;\\n  }\\n  if (value \\u003c min) {\\n    return false;\\n  }\\n  if (value \\u003e= max) {\\n    return false;\\n  }\\n}\\n\\nlet TestContract = function () {\\n  LocalContractStorage.defineMapProperty(this, \\\"grid\\\");\\n};\\n\\nTestContract.prototype = {\\n  init: function () {\\n    for (let y = 0; y \\u003c gridHeight; ++y) {\\n\\n      for (let x = 0; x \\u003c gridWidth; ++x) {\\n        let pixel = {\\n          color : \\\"#FFF\\\",\\n          lastPriceWei : new BigNumber(0),\\n          owner : null\\n        };\\n        this.grid.put(y + \\\"_\\\" + x, pixel);\\n      }\\n    }\\n  },\\n\\n  getGrid: function () {\\n    let result = [];\\n    for (let y = 0; y \\u003c gridHeight; ++y) {\\n      let row = [];\\n      for(let x = 0;x\\u003cgridHeight;x++){\\n        row.push(this.grid.get(y+\\\"_\\\"+x));\\n      }\\n      result.push(row);\\n    }\\n    return result;\\n  },\\n\\n  getRows : function(start, num){\\n    let result = [];\\n    for (let y = start; y \\u003c start+num; ++y) {\\n      let row = [];\\n      for(let x = 0;x\\u003cgridHeight;x++){\\n        row.push(this.grid.get(y+\\\"_\\\"+x));\\n      }\\n      result.push(row);\\n    }\\n    return result;\\n  },\\n\\n  purchasePixels: function (xList, yList, newColorList) {\\n    if (false === Array.isArray(xList)) { throw new Error(\\\"Not an array.\\\"); }\\n    if (false === Array.isArray(yList)) { throw new Error(\\\"Not an array.\\\"); }\\n    if (false === Array.isArray(newColorList)) { throw new Error(\\\"Not an array.\\\"); }\\n\\n    let length = xList.length;\\n    if (length !== yList.length) { throw new Error(\\\"Wrong length.\\\"); }\\n    if (length !== newColorList.length) { throw new Error(\\\"Wrong length.\\\"); }\\n\\n    let newOwner = Blockchain.transaction.from;\\n    let newPrice = Blockchain.transaction.value;\\n    let tmpPrice = newPrice;\\n    for (let index = 0; index \\u003c length; ++index) {\\n      let x = parseInt(xList[index]);\\n      let y = parseInt(yList[index]);\\n      let color = newColorList[index];\\n      if (false === isValidNumber(x, 0, gridWidth)) { throw new Error(`Invalid X ${x}`); }\\n      if (false === isValidNumber(y, 0, gridHeight)) { throw new Error(`Invalid Y ${y}`); }\\n      if (false === isValidColor(color)) { throw new Error(`Invalid Color ${color}`); }\\n      let pixel = this.grid.get(y + \\\"_\\\" + x);\\n      tmpPrice = tmpPrice.minus(pixel.lastPriceWei).minus(priceThresholdWei);\\n      if (tmpPrice.lt(0)) {\\n        throw new Error(\\\"not enough money.\\\");\\n      }\\n    }\\n\\n    let output = [];\\n\\n    for (let index = 0; index \\u003c length; ++index) {\\n      let y = yList[index];\\n      let x = xList[index];\\n\\n      let pixel = this.grid.get(y + \\\"_\\\" + x);\\n\\n      let lastOwner = pixel.owner;\\n      newPrice = new BigNumber(pixel.lastPriceWei).add(priceThresholdWei);\\n      if(lastOwner !== null){\\n        let response = Blockchain.transfer(lastOwner, newPrice.toString());\\n        output.push({\\n          transferSuccess : response,\\n          from : lastOwner,\\n          amount : newPrice.toString()\\n        });\\n      }\\n      pixel.color = newColorList[index];\\n      pixel.owner = newOwner;\\n      pixel.lastPriceWei = newPrice;\\n      //output.push(pixel);\\n\\n      this.grid.set(y + \\\"_\\\" + x, pixel);\\n    }\\n    return output;\\n  },\\n\\n};\\n\\nmodule.exports = TestContract;\\n\",\"Args\":\"\"}\", \"type\":\"deploy\"}"

**Comment by yupnano** [comment]
你好，是使用的最新的主网代码吗？

**Comment by zhaoqijiong** [comment]
是最新master分支的代码

**Comment by dreamflyfengzi** [comment]
由于本地机器性能较低，在5s内未执行完，导致timeout，从而导致无法同步，建议先增加超时时间，同步通过后在恢复。
在transaction_deploy_payload.go 在engine, err := block.nvm.CreateEngine(block, tx, contract, ws)之后 添加 engine.SetExecutionLimits(10*1000*1000); 单位是微秒

**Comment by zhaoqijiong** [comment]
改了代码,然后在467623  又卡住了



[neb-20180620-11.log](https://github.com/nebulasio/go-nebulas/files/2117750/neb-20180620-11.log)

**Comment by yupnano** [comment]
[`SetExecutionLimits(limitsOfExecutionInstructions, limitsOfTotalMemorySize uint64)`](https://github.com/nebulasio/go-nebulas/blob/7470724e2ed1f2f1e54af19e3ead477d324d542e/nf/nvm/engine_v8.go#L238) 是设置合约运行的gasLimit和最大内存。更改运行时间应该使用 [`SetTimeOut(timeout uint64)`](https://github.com/nebulasio/go-nebulas/blob/7470724e2ed1f2f1e54af19e3ead477d324d542e/nf/nvm/engine_v8.go#L233)

在[nf/nvm/engine_v8.go: 326](https://github.com/nebulasio/go-nebulas/blob/7470724e2ed1f2f1e54af19e3ead477d324d542e/nf/nvm/engine_v8.go#L326) 之前添加`e.SetTimeOut(10 * 1000 * 1000)`，时间单位是us
