### ISSUE TITLE
Failed to Setup V8

### ISSUE THREAD

**Issue by notbdu** [nebulasio/go-nebulas#154]
Going through the installation tutorial right now and running into an issue setting up V8. I ran `make deploy-v8` and the `.dylib`s are installed. Here is what I'm running on:
- MacOS High Sierra 10.13.3
- go version go1.10.3 darwin/amd64

Here is the output:
```
user go-nebulas (testnet) $ ./neb -c testnet/conf/config.conf
INFO[2018-06-19T03:30:55-04:00] Setuping Neblet...                            file=neblet.go func="neblet.(*Neblet).Setup" line=111
ERRO[2018-06-19T03:30:55-04:00] V8 Exception:
(null)                          file=logger.go func=nvm.V8Log line=32
FATA[2018-06-19T03:30:55-04:00] Failed to setup V8.                           err="execution failed" file=main.go func=main.runNeb line=111
```

**Comment by yupnano** [comment]
Please run `make dep` again, it should works.

BTW, it's recommended to set the `go-nebulas` project under this path `$GOPATH/src/github.com/nebulasio/go-nebulas`

**Comment by notbdu** [comment]
It's working on current master thanks!
