### ISSUE TITLE
主网交易延迟问题

### ISSUE THREAD

**Issue by zhaoqijiong** [nebulasio/go-nebulas#156]
现在主网交易打包速度好慢，是不是有什么问题？
队列里有近10w条交易等待打包？

![image](https://user-images.githubusercontent.com/1332625/41825021-73bc6f0c-784c-11e8-9e0d-a723ecc14c7e.png)

**Comment by colapig** [comment]
+1 虽然交易量增加了，但最近处理速度变慢了.....
