### ISSUE TITLE
Build last step 'make build' failed

### ISSUE THREAD

**Issue by gavxin** [nebulasio/go-nebulas#157]
I tried build neb but failed on 'make build' with following error. My OS is Debian 9.

```
cd cmd/neb; go build -ldflags "-X main.version=1.0.1 -X main.commit=xxxxxxxxx -X main.branch=analyzer -X main.compileAt=`date +%s`" -o ../../neb-xxxxxxxxxx
# github.com/nebulasio/go-nebulas/vendor/github.com/tecbot/gorocksdb
//usr/local/lib/librocksdb.so: undefined reference to `ZDICT_isError'
//usr/local/lib/librocksdb.so: undefined reference to `ZDICT_trainFromBuffer'
collect2: error: ld returned 1 exit status
Makefile:66: recipe for target 'build' failed
make: *** [build] Error 2
```

Maybe it caused by the rocksdb master branch updated which not compatible with libzstd-dev in apt. It would fix if nebulas specify the version of rocksdb.

**Comment by yupnano** [comment]
It looks like that the rocksDB is not installed correctly.
Please follow the [readme](https://github.com/nebulasio/go-nebulas/blob/master/README.md) or [tutorial](https://github.com/nebulasio/wiki/blob/master/tutorials/) to make sure it installed correctly.

**Comment by 4con** [comment]
Install libzstd from source will solve problem. So, maybe the readme or tutorial should update rocksdb installing instructions? 
I don't think using rocksdb master branch is good idea, that repo is keep updating and no guarantee that works well with current version of nebulas.

**Comment by asnov** [comment]
@4con I had the same issue. You saved me a day. Thank you!
