### ISSUE TITLE
主网又无法同步问题?

### ISSUE THREAD

**Issue by zhaoqijiong** [nebulasio/go-nebulas#158]
最近主网数据量大,新买了ssd硬盘的服务器 ,今天就没法同步区块了
日志里面是这种记录, 旧的机械硬盘的服务器上面也是这样的记录 

新买的服务器啊~~~~

time="2018-06-27T09:25:52+08:00" level=info msg="Starting ChainSync at 299 times." file=sync_task.go func="sync.(*Task).chunkHeadersRequest" line=221 syncPointBlockHash=d391f6fd395cea4c0e59307d55e14019834644a377832d9a520bc66314c9e8da syncPointBlockHeight=495296

![image](https://user-images.githubusercontent.com/1332625/41947764-0b6ed330-79ec-11e8-9617-e8b33f705bc8.png)

![image](https://user-images.githubusercontent.com/1332625/41947818-6bec5944-79ec-11e8-9877-201e97f37e41.png)

**Comment by yupnano** [comment]
您好，您遇到的问题是同步缓慢，还是同步失败呢？

**Comment by zhaoqijiong** [comment]
[neb-20180627-08.log](https://github.com/nebulasio/go-nebulas/files/2139823/neb-20180627-08.log)

**Comment by huhuxiaomomo** [comment]
请问这个问题解决了吗？我页遇到这个问题，您是如何解决的呐？

**Comment by ChengOrangeJu** [comment]
@huhuxiaomomo 看起来日志中的高度仍然在更新，还是在同步数据的过程。请问是否有其他的报错信息

**Comment by huhuxiaomomo** [comment]
谢谢回复，问题是在同步老数据的过程中发生的。已经解决了，531698 这个块中3451378207778243224e22351cea3c1e2211fa3b6ab8c7090284b180cd637c85 这笔交易是超时失败的，但是我根据[#155](https://github.com/nebulasio/go-nebulas/issues/155#issuecomment-402997097) 在engine_v8.go 中把合约执行时间设置的太长了，导致该交易每次因为其他原因（我猜是内存限制，不敢肯定）执行失败，不断重试，把超时时间改回去后，马上就恢复同步了。
