### ISSUE TITLE
How to prevent Ddos attack?

### ISSUE THREAD

**Issue by LeonLi000** [nebulasio/go-nebulas#16]
How to prevent Ddos attack in Nebulas?
If someone maliciously falsifies a lot of invalid transactions to attack our network in Nebulas, our block broadcast and relay will not work. Because the network will be occupied by those invalid transactions.
So, how to prevent Ddos attack?

**Comment by LeonLi000** [comment]
Now I have three ideas.

1. Defines the priority of receiving processing network packet messages. Take precedence over the block message.
2. Avoid message infinite relay and add hop limit. 
3. Limit the frequency of messages from the same node.

So, does anyone have any other idea?

**Comment by fbzhong** [comment]
Latest develop branch includes more functionality to prevent some kind of DDOS attack:
1. priority message queue for sending network message in net model;
2. Guaranteed block producing time, make sure nodes would mint and broadcast block on time. 
3. Seperating the handling process of tx, block and LIB.

**Comment by fbzhong** [comment]
Updated:
1. Add #50 `optimize strategy for message dispatching in network`
