### ISSUE TITLE
[Dapp] Nebulas 会提供实现密钥交换(key exchange)的基础设施吗

### ISSUE THREAD

**Issue by myiwen** [nebulasio/go-nebulas#162]
和不少开发者都聊到过想实现打牌之类的“不完全信息博弈”类的dapp，但是目前在星云链上所有的交易信息都是明文公开的，要实现上述目标，实际就是在一个不安全信道上实现安全(保密)的传输，自然就想到依靠密钥交换(eg. Diffie-Hellman)来做，不知星云有没有这样的基础设施？如果现在没有，未来何时会提供吗？谢谢！

**Comment by ChengOrangeJu** [comment]
暂时需要由客户端加密处理后再上链：）后续有更新会及时发布
