### ISSUE TITLE
wallet

### ISSUE THREAD

**Issue by simplebling** [nebulasio/go-nebulas#163]
My nano wallet always promted of java script error notification. I didn't receive any token😥 what seems to be the prob.?

**Comment by yupnano** [comment]
Hi, could you provide a screen shot? Also the mobile phone and system info is helpful to locate the error.

**Comment by simplebling** [comment]
I can't attach a screen shoot. How? There's no menu for attaching pictures.
My phone number +63 9153010186

**Comment by yupnano** [comment]
you can just paste it here by "Ctrl + V" if the pic is in your system clipboard, or dragging it here if it's a file.

![image](https://user-images.githubusercontent.com/5012612/42746198-351996d0-8909-11e8-909c-67290a4b5d0b.png)

**Comment by simplebling** [comment]
![image](https://user-images.githubusercontent.com/40917285/42761173-58f4358e-893f-11e8-8dfd-39d4ab7f84b8.png)

**Comment by simplebling** [comment]
Hello again. Just send to you the screenshoot of my nano wallet.

**Comment by yupnano** [comment]
This error is because that NasNano cannot connect to  server, have you disabled network access permission for NasNono?

**Comment by Heinoc** [comment]
It was because the network cannot connect our server. Did you have used any network proxy?
And which android version do you using now?

**Comment by simplebling** [comment]
It's andriod 4.4.2 version
Network access is enable
