### ISSUE TITLE
bignumber.js 的版本问题

### ISSUE THREAD

**Issue by haorendashu** [nebulasio/go-nebulas#164]
有没有计划升级 bignumber.js 的版本。

智能合约使用的是 v4.1.0。

neb.js 使用的是 5.0.0：
https://github.com/nebulasio/neb.js/blob/master/package.json#L36 。

官方已经升级到：7.2.1。

**Comment by ChengOrangeJu** [comment]
会考虑在nvm中版本升级，或采用精简的版本，https://github.com/nebulasio/go-nebulas/tree/master/nf/nvm/v8/lib 这边已经有版本的分支
