### ISSUE TITLE
主网同步异常

### ISSUE THREAD

**Issue by leimin78** [nebulasio/go-nebulas#165]
![image](https://user-images.githubusercontent.com/13266516/42865923-b48e7df0-8a9d-11e8-85b0-6e4b4f59dfbb.png)

最近出现了上述错误，以前也经常出现重启能恢复同步，今天重启还是不行。

代码切换到最新的主分支。

**Comment by yupnano** [comment]
请参考这个方案:
https://github.com/nebulasio/go-nebulas/issues/155#issuecomment-402997097

**Comment by leimin78** [comment]
yupnano ,你好哦  这个我早期看到过。 也做了修改了timeout的时间，但这个不能根本解决问题，只是让错误出现的时间延后一点，当出现错误时就必须重启程序。

**Comment by yupnano** [comment]
No, I mean the  comment made at June 6 2018.

#### solution 1 
Please move `go-nebulas` project under this path `$GOPATH/src/github.com/nebulasio/go-nebulas`, then it will not download another `go-nebulas` code under vendor.
#### solution 2 
Remove folder `\vendor\github.com\nebulasio\go-nebulas`. 
Then run `make dep` again.

Another similar issue https://github.com/nebulasio/go-nebulas/issues/154
