### ISSUE TITLE
Does call between contract update to mainnet?

### ISSUE THREAD

**Issue by haorendashu** [nebulasio/go-nebulas#168]
Does call between contract update to mainnet?

when use ``` new Blockchain.Contract ``` it return : 

```
{"result":"TypeError: Blockchain.Contract is not a constructor","execute_err":"Call: TypeError: Blockchain.Contract is not a constructor","estimate_gas":"20181"}
```

**Comment by yupnano** [comment]
Inter-contract call is not released to mainnet yet, please use testnet for the present.
