### ISSUE TITLE
Crypto algorithms compatibility check: using the test suits from Bitcoin/Ethereum to make sure the correctness of crypto algorithms. 

### ISSUE THREAD

**Issue by qywang2012** [nebulasio/go-nebulas#17]
Nebulas crypto contains the transaction's signature and key encryption. Currently, nebulas choose secp256k1 and encrypt as signatures and encryption algorithms, like Bitcoin and Ethereum.

Because of the extensive use of Bitcoin and Ethereum, and their encryption algorithms have been validated, our crypto algorithms need compatibility check: using the test suits from Bitcoin/Ethereum to make sure the correctness of crypto algorithms.

## signature

Nebulas choose `secp256k1 ` as the signature algorithm. We use the bitcoin's libsecp256k1 to sign, verify and recover public key. 

Our testing [files](https://github.com/nebulasio/go-nebulas/tree/develop/crypto/keystore/secp256k1):

```
crypto/keystore/secp256k1/ecdsa_test.go
``` 
We need to verify reliability with the bitcoin test suits.

## encryption

Nebulas choose scrypt as the encryption algorithm. Like Ethereum, Nebulas encrypt the private key in a key file. But the difference is, Ethereum uses `Keccak256 ` to calculate hash and nebulas use `sha3256`. Because of the wide use of Ethereum, Nebulas are also compatible with the keystore of Ethereum. 

Our testing [files](https://github.com/nebulasio/go-nebulas/tree/develop/crypto/cipher):

```
crypto/cipher/scrypt_test.go
```
We need to verify reliability with the Ethereum test suits.

**Comment by fbzhong** [comment]
Yes, we need make sure the 100% correctness of crypto functionality, and also find out and fix the potential vulnerability issues.

I'd suggest we introduce the Test Suits of Bitcoin and Ethereum. If all of them are passed, the behavior of our implementation are consistent with others.
