### ISSUE TITLE
About v8 compile in nvm

### ISSUE THREAD

**Issue by iwojima** [nebulasio/go-nebulas#171]
Dear Team:

I had tried to compile v8 below "~/go/src/github.com/nebulasio/go-nebulas/nf/nvm/v8" ,  i alaways get the error about Error: execution_env.js is not found during i execute function "engine.Call" , as below:

_Error: execution_env.js is not found.  file=logger.go func=nvm.V8Log line=32_

i had checked the code and found that is in "~/go/src/github.com/nebulasio/go-nebulas/nf/nvm/v8/lib/execution_env.cc" , as below:

_int SetupExecutionEnv(Isolate *isolate, Local<Context> &context) {
  char *verlib = NULL;
  if (alvDelegate != NULL) {
    V8Engine *e = GetV8EngineInstance(context);
    verlib = alvDelegate(e, "lib/execution_env.js");
  }
  if (verlib == NULL) {
    return 1;
  }

  char path[64] = {0};
  strcat(path, **verlib**);
  free(verlib);

  char *data = readFile(path, NULL);
  // char *data = readFile("**lib/execution_env.js**", NULL);
  if (data == NULL) {
    isolate->ThrowException(Exception::Error(
        String::NewFromUtf8(isolate, "execution_env.js is not found.")));
    return 1;
  }
_

i want to re-compile the so file and set a absolute path for　execution_env.js , what do you think? or have you better way to cover it?

Thanks!

**Comment by ChengOrangeJu** [comment]
@iwojima Does it work by adding the dir to PATH?

**Comment by iwojima** [comment]
Yes ，I had added the path to make it work ,  i assume that "execution_env.js" is the API provided from nebulasio, is it?

**Comment by Samuelchen85** [comment]
> Yes ，I had added the path to make it work , i assume that "execution_env.js" is the API provided from nebulasio, is it?

Basically, it's one of the library files needed by V8 engine.
