### ISSUE TITLE
智能合约隐藏源码？ how to hide source code of smart contract?

### ISSUE THREAD

**Issue by spiritmg** [nebulasio/go-nebulas#172]
星云用v8引擎来解释智能合约，那么从理论上来讲星云上的智能合约只能开源，没法隐藏源码，对吧？
is there any way to hide the source code of smart contract in nebulas?

**Comment by brandonbevans** [comment]
You can uglify it the JS before you publish smart contract. I think that's the best way as of now.

**Comment by nnnnnAthan** [comment]
先生您好，我是猎头Nathan，在github中看到了您对区块链技术的热爱，现向您推荐火币网的资深java开发工程师的岗位，希望能够与您取得联系！Wechat：16602813234，期待与您联系！
