### ISSUE TITLE
请问普通转账交易时，离线签名交易单，这时的交易体是什么结构，需要包含哪些成员

### ISSUE THREAD

**Issue by gitmakenoise** [nebulasio/go-nebulas#174]
请问普通转账交易时，离线签名交易单，这时的交易体是什么结构，需要包含哪些成员

**Comment by Samuelchen85** [comment]
可以参考我们的wiki: https://github.com/nebulasio/wiki/blob/master/tutorials/%5B%E4%B8%AD%E6%96%87%5D%20Nebulas%20101%20-%2002%20%E5%8F%91%E9%80%81%E4%BA%A4%E6%98%93.md
