### ISSUE TITLE
Build go-nebula on alpine 

### ISSUE THREAD

**Issue by cocoismywife** [nebulasio/go-nebulas#178]
Hi
Could anyone can help? I am running Dockerfile on alpine, when it executing "RUN make deploy-v8", there is some error occurs

`Updating goal targets....
Considering target file 'deploy-v8'.
 File 'deploy-v8' does not exist.
 Finished prerequisites of target file 'deploy-v8'.
Must remake target 'deploy-v8'.
sudo install nf/nvm/native-lib/*.so /usr/local/lib/
Putting child 0x560fcbde8be0 (deploy-v8) PID 37 on the chain.
Live child 0x560fcbde8be0 (deploy-v8) PID 37
Reaping winning child 0x560fcbde8be0 PID 37
sudo /sbin/ldconfig
Live child 0x560fcbde8be0 (deploy-v8) PID 38
Reaping losing child 0x560fcbde8be0 PID 38
make: *** [Makefile:58: deploy-v8] Error 1
Removing child 0x560fcbde8be0 PID 38 from chain.`

Who has met before?

**Comment by CreateGitHub** [comment]
lib64

**Comment by cocoismywife** [comment]
> lib64
Hi CreateGitHub

Thank you very much.

But could you give me more detail, I am not familiar with c/c++ build system. What should I need to do next? Copy the *.so to /usr/lib64. Please specify me whether right or not.

**Comment by Samuelchen85** [comment]
We haven't tested on alpine yet, so there would be some unexpected issues.  

Mac and Ubuntu are fully supported, would highly recommend building nebulas on one of those two platforms.

**Comment by Samuelchen85** [comment]
Since it's not supported at this moment, I'm gonna close it now. Once we have progress on this, will announce it to the community.
