### ISSUE TITLE
Add more command line options.(commands & flags)

### ISSUE THREAD

**Issue by qywang2012** [nebulasio/go-nebulas#18]
Nebulas uses [urfave/cli](https://github.com/urfave/cli) for building command line apps in Go. Currently, nebulas only provide few commands and flags, we need more command line options.

## Commands

Nebulas have added some commands:

* `accountCommand`: Account new, import, list and update etc.
* `consoleCommand`: Neb console implementation.
* `networkCommand`: Manage nebulas network

We need more commands like:

* `configCommand`: Generate or update config file.
* `dumpCommand`: Dump a specific block from storage. 
* `versionCommand`: Show version.
* More commands...

## Flags

Nebulas have added flags:

* `config`: Load config file

We need more flags like:

* `config field`: All config field should add for neb.
* Other more flags...

**Comment by LeonLi000** [comment]
@fbzhong @qywang2012 
I added some command in Nebulas. 

`chaincmd`

- dumpblock  Use "./neb dump 10" to dump 10 blocks before tail block.

`misccmd`

- version  Use "./neb version" to get the version of Nebulas.
- license   Use "./neb license" to get Nebulas license info.

`configcmd`

- config new   Use "./neb config new [filename]" to generate a default config file.
