### ISSUE TITLE
Docker builds failed "testnet"

### ISSUE THREAD

**Issue by uranus97s** [nebulasio/go-nebulas#187]
cd cmd/neb;   go build -ldflags "-X main.version=1.0.8.1 -X main.commit=37620b622a9901dd3d7aa945f22cb0e49b44b698 -X main.branch=testnet -X main.compileAt=`date +%s`" -o ../../neb-37620b622a9901dd3d7aa945f22cb0e49b44b698
# github.com/nebulasio/go-nebulas/nf/nbre
/usr/bin/ld: cannot find -lnbre_rt
collect2: error: ld returned 1 exit status
make: *** [build] Error 2
Makefile:98: recipe for target 'build' failed
The command '/bin/sh -c make build' returned a non-zero code: 2

**Comment by qywang2012** [comment]
We have update docker for testnet (Currently only support ubuntu). You can retry it.
