### ISSUE TITLE
ls there a plan to support go module?

### ISSUE THREAD

**Issue by csunny** [nebulasio/go-nebulas#189]
As we all known,  go module  has been released at go 1.11,  and it's more Simple and practical
than other tools,  is there a plan to use go module? 

when?

**Comment by Samuelchen85** [comment]
For now, we do not have a concrete timeline to switch to go module. While it's definitely better to use it down the road. 

Nebulas is going for community collaboration right now, so if you're interested in working on this, you can actually propose this as a project on the Nebulas Community Collaboration Platform (https://go.nebulas.io).
