### ISSUE TITLE
Tutorials链接失效

### ISSUE THREAD

**Issue by buster719** [nebulasio/go-nebulas#190]
https://wiki.nebulas.io/en/latest/dapp-development/mainnet.html
该页面下的Tutorials板块，链接最后缺少.md，导致无法打开。

**Comment by smalloranges** [comment]
感谢支持。关于wiki的issue请报在wiki下面：[https://github.com/nebulasio/nebdocs/issues](https://github.com/nebulasio/nebdocs/issues)，谢谢。
这个404链接是内容搬迁丢失所致，我们会修复的。也欢迎一起协作编辑呀。编辑wiki还有bounty的呀。
