### ISSUE TITLE
I have some NAS_ETH coin,but I don't know how to make them to NAS

### ISSUE THREAD

**Issue by cyinginwhu** [nebulasio/go-nebulas#193]

**Comment by Samuelchen85** [comment]
The NAS token swap was already closed, you may wanna check gate.io to see if you can still swap the erc20 token for NAS mainnet token there. 
Should you have any further question, please send email to: contact@nebulas.io directly. 
Issues submitted here are only for tech issues related with nebulas protocol. 
Thanks!
