### ISSUE TITLE
failed to build NEB

### ISSUE THREAD

**Issue by prettyCoders** [nebulasio/go-nebulas#196]
![image](https://user-images.githubusercontent.com/36216120/58926665-91028000-877e-11e9-8c3e-eb8a3410a0ec.png)
![image](https://user-images.githubusercontent.com/36216120/58926688-9d86d880-877e-11e9-87ac-380b57a46087.png)

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/58926858-2d2c8700-877f-11e9-856f-3e284721d89e.png)

**Comment by Samuelchen85** [comment]
Update your local proto and protoc-gen-go, the version probably is old.  The protobuffer source files in go-nebulas were generated based on 3.6.1.

**Comment by prettyCoders** [comment]
thanks
