### ISSUE TITLE
error while loading shared libraries: libc++.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by prettyCoders** [nebulasio/go-nebulas#197]
![image](https://user-images.githubusercontent.com/36216120/58933202-12ffa280-8799-11e9-8695-b6633668fe6b.png)
#

**Comment by prettyCoders** [comment]
I installed libc++1 and libc++abi1,But now there is a new problem,
![image](https://user-images.githubusercontent.com/36216120/58933509-0def2300-879a-11e9-9509-94d5c44b7331.png)

**Comment by Samuelchen85** [comment]
The root cause is that your env variable "LD_LIBRARY_PATH" does not include the location of the corresponding libraries.

If you have the libraries generated/installed in "nbre/lib", you can run the script "install-native-libs.sh"(which is in go-nebulas root dir) to configure the LD_LIBRARY_PATH.

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/58934416-02512b80-879d-11e9-8794-df8619a1a51b.png)

**Comment by prettyCoders** [comment]
@Samuelchen85

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/58934501-3af10500-879d-11e9-88af-b213d3f65795.png)

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/58934600-83a8be00-879d-11e9-8285-ff86585a302c.png)
thanks

**Comment by Samuelchen85** [comment]
Awesome！Glad that the problem was solved.
