### ISSUE TITLE
neb-crashreporter not found

### ISSUE THREAD

**Issue by prettyCoders** [nebulasio/go-nebulas#198]
![image](https://user-images.githubusercontent.com/36216120/59188944-6f086380-8bab-11e9-8459-6c8b9a28b149.png)

**Comment by prettyCoders** [comment]
create one file? or  directory ?

**Comment by Samuelchen85** [comment]
neb-crashreporter is not generated, however, we do not really need it.

To get rid of the error, you can change the option "enable_crash_report" to be false in the default configuration file(conf/default/config.conf).

**Comment by prettyCoders** [comment]
OK，Thanks 

发自我的iPhone

------------------ Original ------------------

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/59238360-67d76900-8c30-11e9-86d4-7737116c5a12.png)
![image](https://user-images.githubusercontent.com/36216120/59238369-732a9480-8c30-11e9-82d8-0c52366409af.png)
What happened?

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/59248524-40df5e00-8c55-11e9-96a0-6f6ac14166cc.png)

**Comment by Samuelchen85** [comment]
Find where the nbre.db is located, and see if the binary code files (*_auth1.bc, *_nr1.bc, *_dip1.bc) were generated. If not, then you need to check if clang was built sucessfully and is working properly.

**Comment by prettyCoders** [comment]
thanks!But .........
![image](https://user-images.githubusercontent.com/36216120/59251686-011c7480-8c5d-11e9-949e-daed9e81d95e.png)

**Comment by prettyCoders** [comment]
![image](https://user-images.githubusercontent.com/36216120/59252322-72105c00-8c5e-11e9-9792-2cb3a21ea10f.png)

**Comment by prettyCoders** [comment]
It`s my data
![image](https://user-images.githubusercontent.com/36216120/59252644-1abebb80-8c5f-11e9-89ef-853f4a92d16a.png)

**Comment by qywang2012** [comment]
It appears that your .bc file did not compile successfully. What is your system environment? We recommend using Ubuntu 16.04. Or you can use our docker version.

**Comment by prettyCoders** [comment]
ubuntu16.04,what should i do.

**Comment by xianglinhe** [comment]
> neb-crashreporter is not generated, however, we do not really need it.
> 
> To get rid of the error, you can change the option "enable_crash_report" to be false in the default configuration file(conf/default/config.conf).

should update the codes if it's not used.

**Comment by qywang2012** [comment]
@xianglinhe I will update the config , Thanks.
