### ISSUE TITLE
Failed to verify block

### ISSUE THREAD

**Issue by Kenyre** [nebulasio/go-nebulas#201]
Hi there,

Recently our node stopped syncing, with the following error message in neb.log:
```
time="2019-08-14T06:32:15Z" level=info msg="Failed to verify block." block="{\"height\": 2884998, \"hash\": \"ae9eba52f70c9ba0beba22947d970a04cd39557fdb5890882a1f96e43e8ab6c0\", \"parent_hash\": \"11d591c610b7ca0aacf27a6a2cebd22c7f2983ec53974ca5e755883f25f409cd\", \"acc_root\": \"d8348b22e5dc3a88e4c00a838b145f46463809d59106aec1404e9bc677f5a20e\", \"timestamp\": 1565764335, \"tx\": 0, \"miner\": \"n1PWmA94txbaguGi8CnfkWfkcn8UNsHZLnP\", \"random\": \"/vrf_seed/15163ec419d90b6ed0bd90e11c3b1f604e32f5c4d05a489199a7b1173dae57db/vrf_proof/57f1d4f2f95e91c9112137d303a7c64ee5304a27bb14169eeccfafab707f139802fae1cdea3bad75224fc2d3e2d99db0f59cf4c1119b8a0f3eee2f596f9323e004378d5ca9e8cb53d6eb834ff5a849cdbfe0415188e9d11dbfec6966a770421890babe38f6c634ba180dd8ae2af0b3604281cb43ab89c2e3fe35a43877a4184918\"}" err="invalid block proposer" file=block_pool.go func="core.(*BlockPool).push" line=365
```
This started happening after block 2850042 (which is the latest which can be requested over rpc). I decided to delete the block store and download your snapshot. This morning however i discovered that the same error at the same block occurred again. Any idea on how i might fix this?

**Comment by qywang2012** [comment]
You should upgrade the node code to the latest version, which can be compiled using [master](https://github.com/nebulasio/go-nebulas) branch or tag [v2.1.0](https://github.com/nebulasio/go-nebulas/tree/v2.1.0)
