### ISSUE TITLE
Event functionality

### ISSUE THREAD

**Issue by fbzhong** [nebulasio/go-nebulas#25]
Since Smart Contract and Transaction is executed in async way, submit and wait. As a developers or users, they are want to know when the submitted tx is onchain, or notice them it's done.

So in nebulas, we introduce the ```Event``` functionality, as the following:
1. Smart Contract developers can define their own ```Event``` in Smart Contract. After successful execution, the events will be triggered in order.
2. Developers can subscribe the successful events.

**Comment by fbzhong** [comment]
@royshang For the event, we may need a trie to store them and keep them consistent.

**Comment by fbzhong** [comment]
@LeonLi000 the event functionality in Network/Dispatcher should be use the commit above.

**Comment by fbzhong** [comment]
We should follow up the following working items:
1. add ```Event``` trie and ```Event Hook``` in Core for ```ChainEventCategory```, by @royshang 
2. add ```Event Hook``` in Network for ```NodeEventCategory```, by @LeonLi000 
3. add ```Server Push RPC API``` in rpc, by @qywang2012 
we can use ```Server streaming RPCs``` in gRPC, have no idea in HTTP.
4. add ```Event``` functionality and ```Event Hook``` in NVM for ```ChainEventCategory```, by @fbzhong

**Comment by royshang** [comment]
done.
