### ISSUE TITLE
send p2p message in nebulas should add retry strategy

### ISSUE THREAD

**Issue by LeonLi000** [nebulasio/go-nebulas#28]
we implemented send p2p message method in nebulas. 
```go
SendMsg(name string, msg []byte, target string)
```
but we are supposed to give a retry strategy when send message failed. when we download the block from a node, we hope the sooner the better. in this case, we hope to try again when we fail.
so we should add retry strategy in nebulas p2p network.

**Comment by fbzhong** [comment]
The retry algorithm is about Connection Reconnecting and Message Resending.
Let's close this issue and submit new issue to discuss Reconnecting strategy and Message resending.
