### ISSUE TITLE
RPC:使用curl连接http://localhost:8090/v1/user/accountstate 返回404错误

### ISSUE THREAD

**Issue by luoam** [nebulasio/go-nebulas#29]
#### 源代码：
下载的是release中的v0.4.0版本，以及vender.tar.gz文件
#### ubuntu 16.04
分别使用一台物理机运行seed-node,另一台物理机运行normal-node

使用ss -ant查看端口，8090端口已经打开。
运行
`curl -i -H Accept:application/json -X POST http://localhost:8090/v1/user/accountstate -d '{"address":"1a263547d167c74cf4b8f9166cfa244de0481c514a45aa2c"}'`
返回的是404 Not Found
### 附件
normal.log是保存的普通节点的neb运行信息
seed.log 是种子节点的neb运行信息
### 另外
./neb console  api.** 接口操作正常。

[normal.log](https://github.com/nebulasio/go-nebulas/files/1591588/normal.log)
[seed.log](https://github.com/nebulasio/go-nebulas/files/1591590/seed.log)

**Comment by luoam** [comment]
### 补充一下
我无法通过make dep， 因此是直接按照教程下载的vender文件夹

**Comment by qywang2012** [comment]
测试网发布后更新到v0.5.0版本，请使用新版
