### ISSUE TITLE
seed node can't sync with others if it's offline for a long time.

### ISSUE THREAD

**Issue by royshang** [nebulasio/go-nebulas#30]
Requirement:
I start a seed node and six normal nodes, the normal nodes will connect to the seed node at first. They can sync with each other very well when all are online. 

Situation:
After a few minutes, I stop the seed node for a long time and then restart it. The normal nodes will discover the seed node again, and send the newest block to it. Now the seed node will receive many blocks whose parent can't be found locally.

for example. 
seed node: genesis -> 0 -> 1 -> ... -> 10.
normal nodes: genesis -> 0 -> 1 -> ... -> 10 -> ... -> 100.
seed node will receive the block at height 100 from others.

In general, if the gap between new received block and the local tail block is small, we will use downloader to download the blocks in the gap. But if the gap is big enough, we will restart sync manager to sync blocks from others.

Problem:
In the situation described above, the seed node should restart sync but it didn't.

**Comment by fbzhong** [comment]
Hi Roy,

Since we adopt new sync strategy, sync with chunks instead of blocks. Is this issue still exists? If not, this case should be closed.

**Comment by royshang** [comment]
can be closed.
