### ISSUE TITLE
seed-node停止运行时，normal-node会意外停止

### ISSUE THREAD

**Issue by luoam** [nebulasio/go-nebulas#31]
#### 测试环境
ubuntu 16.04,
nebulas v0.4.0, 
go 1.9.2,
dep 0.3.2
#### 测试过程如下

1. 先在192.168.31.106上运行seed-node

2. 然后在192.168.31.100上运行normal-node

3. 第1、2步两个节点都正常运行

4. 在seed-node上CTRL+C终止neb进程，此时normal-seed的进程也终止了

**我的猜想**
也就是说在没有没有种子节点的情况下，普通节点将无法运行。另一种情况就是，假设网络中的种子节点挂掉，那么与这个种子节点连接的普通节点会全部挂掉，这样会不会导致网络不稳定。
**再说说我的理解：**
我的理解是这样的，对与普通节点来说，当出现一个种子节点挂掉时，应该自动去寻找网络中的其他种子节点
#### 附件
附件是程序终止时normal-node的日志

[error201712292007.log](https://github.com/nebulasio/go-nebulas/files/1593091/error201712292007.log)

**Comment by LeonLi000** [comment]
@luoam Yes, you are right. If the seed down, the node should look for the other nodes to connect.
I will fix it very soon.

**Comment by fbzhong** [comment]
Hi Luoam,

New network layer would fix that bug, you may have a try at the latest develop branch.

**Comment by fbzhong** [comment]
New develop branch code fixed this bug.
