### ISSUE TITLE
测试链的同步过程在网络中途中断时后停止同步，网络恢复而同步没有恢复

### ISSUE THREAD

**Issue by luoam** [nebulasio/go-nebulas#32]
nebulas v0.5.0

1. 在启动节点后，开始同步，中途网络中断，nebulas进程显示仍然在运行，通过
`curl -i -H Accept:application/json -X GET http://localhost:8685/v1/user/nebstate`
显示peer_count=1

2. 网络重新恢复，此时，再次查看nebstate，peer_count=1

网络中断后和网络恢复之后查看
`curl -i -H Accept:application/json -X POST http://localhost:8685/v1/user/accountstate -d '{"address":"0b9cd051a6d7129ab44b17833c63fe4abead40c3714cde6d"}'`
显示的balance一样，
根据这种情况，推断应该是同步过程在网络中断之后停止了，网络重新恢复之后同步进程没有恢复

**Comment by fbzhong** [comment]
The Sync strategy and implementation still need optimization. Pls watch our commits, we are fixing them.

**Comment by fbzhong** [comment]
New sync implementation fixed this issue, close it.
