### ISSUE TITLE
Nebulas status page

### ISSUE THREAD

**Issue by qywang2012** [nebulasio/go-nebulas#35]
We are glad to release Nebulas Testnet. We need a status page to show the network running state. The contents of state page at here:
* running state by area:
  * testnet-cal
  * testnet-can
  * testnet-lon
  * testnet-par
  * testnet-jan
  * testnet-sin
  * testnet-vir
  * testnet-hkg
  * testnet-ger
* api running status
* block status
  * block height
  * block hash
  * expected miner(GetDynasty & BlockDump)
* transaction status
  * submits count
  * execution  success count
  * execution fail count
  * contracts count(optional)

* history status records

**Comment by fbzhong** [comment]
Is this feature implemented? If so, close it. @larry

**Comment by qywang2012** [comment]
It implemented by @luoam, Thanks very much!
