### ISSUE TITLE
Can't find seed seed.conf file

### ISSUE THREAD

**Issue by Tester1988** [nebulasio/go-nebulas#36]
Thank you for a great tutorial

I am stuck on the creation block configuration part of the tutorial

I can't seem to find the seed.conf file under the go-nebulas/conf/default. 

I have the genesis.conf and config.conf  files

Please advise what steps I may have missed.

Thank you

**Comment by qywang2012** [comment]
Sorry, I have not update tutorial on it. The tutorial has updated now.
https://github.com/nebulasio/wiki/blob/master/tutorials/%5BEnglish%5D%20Nebulas%20101%20-%2001%20Installation.md
