### ISSUE TITLE
is stream_manager in net/p2p necessary?

### ISSUE THREAD

**Issue by yyh1102** [nebulasio/go-nebulas#39]
[Source code](https://github.com/nebulasio/go-nebulas/blob/develop/net/p2p/stream_manager.go)
In libp2p, streams are multiplexed over single connections so, unlike connections themselves, they are cheap to create and dispose of. We can newa stream when we want to send message and close it after receiving response.  
Why the nebulas needs to reuse a stream and holds only one stream to a certain peer at the same time?
What's the stream_manager actually used for?

**Comment by fbzhong** [comment]
Hi @yyh1102 

In nebulas p2p, the stream_manager.go is used to manage streams/connection.

As you are trying to tell us, the stream in libp2p are multiplexed over single connection. So that means nebulas could not manage those connections, new stream if needed, close stream after used.

If so, I still have one more question: when the libp2p release/close the actual tcp/connection?

**Comment by yyh1102** [comment]
Thanks for replying.
As i know, there is no api to release/close the actual tcp connection in libp2p. So what you mean is that nebulas treat a stream as a "tcp connection", and design a upper layer protocol on it, which is neb_message. And if a stream close, we believe the connection to the peer is closed, whether the real tcp connection is closed or not. right?

**Comment by fbzhong** [comment]
Sorry for late reply. 

The stream manager is used to manage all active streams, or tcp connection exactly. In traditional network model, it will significantly improve performance by using keep alive long tcp connection. 
I did not run a perf test on this model for libp2p, so I just bring this design into nebulas directly.

**Comment by yyh1102** [comment]
Never mind.

Yes you are right. I just found out the streams in libp2p are running over a keep-alive long tcp connection so the streams may be treat as the same level as `http` protocol. I'm just using libp2p to create a p2p project, and i would like to share if i have done some perf test of 'using streams without manager'. : )

**Comment by fbzhong** [comment]
Cool, thanks for letting us know the underlying mechanism of libp2p. 

We are very glad you would do any contribution to nebulas, and I think you definitely will. 

Keep in touch. 加油💪
