### ISSUE TITLE
Can't start node (develop branch)

### ISSUE THREAD

**Issue by maartendq** [nebulasio/go-nebulas#48]
Hi,

Trying to connect a linux node to testnet but I get the following error:

./neb -c conf/testnet-config.conf 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xc204cf]

goroutine 1 [running]:
github.com/go-nebulas/vendor/github.com/nebulasio/go-nebulas/neblet.New(0xc420232c60, 0xc420058840, 0xa, 0x0)
	/go/src/github.com/go-nebulas/vendor/github.com/nebulasio/go-nebulas/neblet/neblet.go:81 +0x3f
main.makeNeb(0xc42009af20, 0xc420230c70, 0xc420165c38, 0xafa275)
	/go/src/github.com/go-nebulas/cmd/neb/main.go:170 +0x15a
main.neb(0xc42009af20, 0xc42009af20, 0xc420165c1f)
	/go/src/github.com/go-nebulas/cmd/neb/main.go:87 +0x2f
github.com/go-nebulas/vendor/github.com/urfave/cli.HandleAction(0xcef420, 0xf96340, 0xc42009af20, 0xc420067140, 0x0)
	/go/src/github.com/go-nebulas/vendor/github.com/urfave/cli/app.go:490 +0xd2
github.com/go-nebulas/vendor/github.com/urfave/cli.(*App).Run(0xc420070ea0, 0xc42006e060, 0x3, 0x3, 0x0, 0x0)
	/go/src/github.com/go-nebulas/vendor/github.com/urfave/cli/app.go:264 +0x635
main.main()
	/go/src/github.com/go-nebulas/cmd/neb/main.go:83 +0xbc1

PS: I've built neb from develop branch

**Comment by fbzhong** [comment]
Thanks for reporting bugs. We will handle them.

**Comment by qywang2012** [comment]
Thanks for reporting bugs.
