### ISSUE TITLE
panic: unsupported go version go1.9.3

### ISSUE THREAD

**Issue by jiaodong** [nebulasio/go-nebulas#49]
Following instructions on: https://github.com/nebulasio/wiki/blob/master/tutorials/%5BEnglish%5D%20Nebulas%20101%20-%2001%20Installation.md

Environment: MacOS, homebrew go version: 1.9.3

After setting up all dependencies and git clone from master, executing ./neb command would fail with unsupported go version error (see title). 

Possible reason: gorountine package used in vendor/github.com/huandu/goroutine/info.go which uses https://github.com/huandu/goroutine/ that doesn't have go 1.9.3 runtime supported

**Comment by fbzhong** [comment]
Hi Roy,

Please follow this bug. The goroutine package does not support go 1.9.3, which caught crash.

**Comment by qywang2012** [comment]
I have removed the dependency on [goroutine](https://github.com/huandu/goroutine), now go-nebulas support the go-v1.9.3
