### ISSUE TITLE
Limit the number of socket requests

### ISSUE THREAD

**Issue by LeonLi000** [nebulasio/go-nebulas#51]
During the stress test last night, there was a problem that leveldb could not write.
I got this error:
```
err="open data.db/035303.ldb: too many open files" 
```
Our system is ubuntu. I looked at the maximum number of files that the system allocated for `neb` to open. The soft limit is 1024.
![image](https://user-images.githubusercontent.com/6380914/35553189-c5a42a32-05d1-11e8-9d76-51bad1f80731.png)

This error means that the number of fds opened by `leveldb` exceeds the number of system allocations. 

However, I found that the number of fds occupied by `leveldb` was far lower than the number of fds allocated by the system.  The maximum number of files that leveldb can open by default is 500. It only takes up 300 fds.
Then, I found that `socket` takes up a lot of fds. It takes up 700 fds.

Therefore, we may need to limit the number of socket requests in our process, otherwise it will directly affect the stability of the neb system.

Why do we have so many sockets in our process?
In nebulas, Neb streams and rpc invoke  and http requests all can create sockets.
The stress test created a lot of http sockets, and then took up a lot of fds.

So, How to limit the number of socket requests in our process?

First, we can limit the number of streams in nebulas. For example, we can limit the number of streams to 100, and we don't deal with streams that exceed 100.

Then the maximum number of files that leveldb can open by default is 500.

 And then we need to limit the number of sockets created through HTTP and RPC. This may be a little more difficult.（TODO）

We can even configure the number of fds for sockets and leveldb to our configuration files as advanced features for configuration files.

**Comment by LeonLi000** [comment]
this `0a9bb77e7cb7c743018a312ad69883c75827d104` commit have implemented to limit the number of sockets created through HTTP and RPC.

**Comment by smartpunter** [comment]
Please note, that standart limit for files descriptors is very low for highload systems. Normal recomendations for servers with big network load is to increase it to 32, or even 128k. You might want to ask the user to set this limits higher and then obey the set limits. Something like this, for Ubuntu:

/etc/security/limits.conf
* soft nofile 32768
* hard nofile 131072
/etc/systemd/system.conf
DefaultLimitNOFILE=131072
DefaultLimitNPROC=131072

**Comment by fbzhong** [comment]
Yes, we are aware that, thanks for reminder. 

In current design, we’d like the user controls the ‘limits of max open files’. For the ‘neb’, the two things should be supported:
1. Make sure the ‘fd of leveldb and necessary network peers’ are guaranteed, wouldn’t encounter the ‘too may open files’ issue. 
2. User could config the limits for both neb and rpc connections.
