### ISSUE TITLE
Nebulas RPC subscribe interface issue

### ISSUE THREAD

**Issue by qywang2012** [nebulasio/go-nebulas#61]
Nebulas subscribe interface using the long connection, RPC using gRPC connection, the long connection by a stream can work well. However, in the HTTP request, using the keep-alive can request but don't return data.

#### gRPC usage
```go
	addr := fmt.Sprintf("127.0.0.1:%d", uint32(8684))
	conn, err := rpc.Dial(addr)
	if err != nil {
		log.Fatal(err)
	}
	defer conn.Close()

	ac := rpcpb.NewApiServiceClient(conn)

	stream, err := ac.Subscribe(context.Background(), &rpcpb.SubscribeRequest{})

	if err != nil {
		log.Fatalf("could not subscribe: %v", err)
	}
	for {
		reply, err := stream.Recv()
		if err == io.EOF {
			break
		}
		if err != nil {
			log.Printf("failed to recv: %v", err)
		}
		log.Println("recv notification: ", reply.Topic, reply.Data)
	}
```
#### http usage
`curl` and the JS implementation of the `RPC` don't seem to return the data properly because the data is encoded in chunks.
```js
const http = require("http")

callback = function(response) {
  response.on("data", function(chunk) {
    console.log(chunk.toString("utf8"))
  })
}

var req = http.request(
  {
    host: "localhost",
    port: 8685,
    path: "/v1/user/subscribe",
    method: "POST",
    headers: { "Content-Type": "application/json" },
  },
  callback
)
req.on("error", function(e) {
  console.log("problem with request: " + e.message)
})
req.write('{"topics":["chain.executeTxSuccess"]}')
req.end()
```
Anybody has a better way to handle the Subscribe via http?

####  issue
The event emitter is a non-blocking design, evnent data will be lost when the channle is full when there are many subscribed events. Since the RPC stream is sent serially, the message is not delivered in time. We need a non-blocking pipeline for event collection. Can anyone alse take this job, using kafka, redis, etc as the adapter?

The events in event trie May not response in Subscribe, This may be a bug in event emitter.

**Comment by fbzhong** [comment]
Hi Larry,

How's this issue? Any updates?

**Comment by 1c7** [comment]
Any update?
Why close this issue?

**Comment by 1c7** [comment]
### How to **Reliably** listen to event emit by specific Smart Contract?
For example: NRC20 token, 

[Following code come from official doc](https://github.com/nebulasio/wiki/wiki/NRC20)
```js
    transfer: function (to, value) {
        value = new BigNumber(value);

        var from = Blockchain.transaction.from;
        var balance = this.balances.get(from) || new BigNumber(0);

        if (balance.lt(value)) {
            throw new Error("transfer failed.");
        }

        this.balances.set(from, balance.sub(value));
        var toBalance = this.balances.get(to) || new BigNumber(0);
        this.balances.set(to, toBalance.add(value));

        this.transferEvent(true, from, to, value); // <--------------How do I listen to this?
    },
```

**Comment by 1c7** [comment]
Do I **have to** run a local node myself? and do this?

![image](https://user-images.githubusercontent.com/1804755/53679122-531b3900-3d03-11e9-8b87-21f2ec60d73d.png)

**Comment by 1c7** [comment]
Doc: https://github.com/nebulasio/wiki/blob/master/rpc.md#subscribe
![image](https://user-images.githubusercontent.com/1804755/53679266-557e9280-3d05-11e9-8e8d-e015ba56cb6b.png)

**Comment by 1c7** [comment]
Seem like I can't subscribe to specific *one* Smart Contract? 
`subscribe` seem like return all event?
