### ISSUE TITLE
installation error

### ISSUE THREAD

**Issue by AlexLisong** [nebulasio/go-nebulas#65]
Hi, we are trying to get it up on our mac, 
when we run

**make dep**

we got this error:

**dep ensure -v
The following issues were found in Gopkg.toml:

  ✗ unable to deduce repository and source type for "leb.io/hashland": unable to read metadata: unable to fetch raw metadata: failed HTTP request to URL "http://leb.io/hashland?go-get=1": Get http://leb.io/hashland?go-get=1: dial tcp 104.131.190.18:80: getsockopt: connection refused

ProjectRoot name validation failed
make: *** [dep] Error 1**

any idea?
Thanks,

**Comment by qywang2012** [comment]
@AlexLisong pull the latest commit and then `make dep` again, we have fixed this issue.
