### ISSUE TITLE
Transactions with non-positive gas limit should not be pushed into transaction pool

### ISSUE THREAD

**Issue by ChengOrangeJu** [nebulasio/go-nebulas#66]
In Nebulas, transactions from RPC, console or http are carefully verified before they are pushed into transaction pool. The verification contain several steps, such as the minimum value of gas price , the correctness of signature, etc. 

There is one more check we need to add to this process: the gas limit of the transaction should be greater than 0, otherwise it will be blocked from the transaction pool. 

It should be noted that such a transaction will also not be executed in the old process. 

```
func (pool *TransactionPool) push(tx *Transaction) error {
        ...
        if tx.gasLimit.Cmp(util.NewUint128().Int) <= 0 {
		metricsTxPoolGasLimitLessOrEqualToZero.Inc(1)
		return ErrGasLimitLessOrEqualToZero
	}
        ...
}
```

**Comment by qywang2012** [comment]
good job!
