### ISSUE TITLE
Cannot find package "context" while building.

### ISSUE THREAD

**Issue by Umiiii** [nebulasio/go-nebulas#80]
go version go1.6.2 linux/amd64
Error message:
root:~/go/src/github.com/nebulasio/go-nebulas# make build
cd cmd/neb; go build -ldflags "-X main.version=0.7.0 -X main.commit=8242212a8571023f3cfc903ea44280a74a25d27a -X main.branch=master -X ma
in.compileAt=`date +%s`" -o ../../neb-8242212a8571023f3cfc903ea44280a74a25d27a
../../vendor/github.com/influxdata/influxdb/client/influxdb.go:7:2: cannot find package "context" in any of:
        /root/go/src/github.com/nebulasio/go-nebulas/vendor/context (vendor tree)
        /usr/lib/go-1.6/src/context (from $GOROOT)
        /root/go/src/context (from $GOPATH)
Makefile:66: recipe for target 'build' failed
make: *** [build] Error 1

**Comment by qywang2012** [comment]
@Umiiii The min version of nebulas required is >= 1.9.0

**Comment by Umiiii** [comment]
@qywang2012 I see. Thanks.
