### ISSUE TITLE
Docker builds failed on Ubuntu.

### ISSUE THREAD

**Issue by Umiiii** [nebulasio/go-nebulas#81]
sudo install nf/nvm/native-lib/*.so /usr/local/lib/
sudo /sbin/ldconfig
cd cmd/neb; go build -ldflags "-X main.version=0.7.0 -X main.commit=ce42d8a2aae0ee0f2deaaa759326d5917aa7d528 -X main.branch=develop -X main.compileAt=`date +%s`" -o ../../neb-ce42d8a2aae0ee0f2deaaa759326d5917aa7d528
#github.com/nebulasio/go-nebulas/vendor/github.com/tecbot/gorocksdb
../../vendor/github.com/tecbot/gorocksdb/backup.go:4:24: fatal error: rocksdb/c.h: No such file or directory
 // #include "rocksdb/c.h"
                        ^
compilation terminated.
Makefile:66: recipe for target 'build' failed
make: *** [build] Error 2
The command '/bin/sh -c go get -u github.com/golang/dep/cmd/dep &&     go get -u golang.org/x/tools/cmd/goimports &&     make dep &&     make deploy-v8 &&     make build' returned a non-zero code: 2
root@zen2-test:~/go-nebulas# 

All I do is just git clone the repository and run `docker build -t nebulas .`

OS: Ubuntu 16.04 x64
Kernel:Linux zen3 4.4.0-109-generic #132-Ubuntu SMP Tue Jan 9 19:52:39 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Umiiii** [comment]
..And when I build rocksdb in the environment,here is another error:

> /usr/bin/ld: warning: libv8_libplatform.so, needed by ../../nf/nvm/native-lib/libnebulasv8.so, not found (try using -rpath or -rpath-link)
/usr/bin/ld: warning: libv8.so, needed by ../../nf/nvm/native-lib/libnebulasv8.so, not found (try using -rpath or -rpath-link)

**Comment by Umiiii** [comment]
I think you guys may just test it on macOS and no one run it on Ubuntu right?

**Comment by yupnano** [comment]
It seems that you have not installed the required dependencies.
Please follow the [Readme ](https://github.com/nebulasio/go-nebulas/blob/develop/README.md) or [tutroials](https://github.com/nebulasio/wiki/tree/master/tutorials) step by step to make sure all the dependencies is installed. And then you can build it successfully. 
If you still encounter some errors , please reply here with the error information.

**Comment by royshang** [comment]
Dockerfile has been updated now. Pls check it again.
