### ISSUE TITLE
node stop syncing at 52765

### ISSUE THREAD

**Issue by bitcodernull** [nebulasio/go-nebulas#82]
the error info:

![image](https://user-images.githubusercontent.com/35094762/38553020-827db15a-3cf0-11e8-96d9-235140c028f0.png)

how to resolve it?
thanks

**Comment by royshang** [comment]
@bitcodernull could we have more details of the runtime? Maybe you can send us the log file via Email(roy@nebulas.io).

**Comment by bitcodernull** [comment]
I have sent the log file from bitcodenull@gmail.com
thanks

**Comment by royshang** [comment]
@bitcodernull I found the execution failure in your log as following.
![image](https://user-images.githubusercontent.com/3244584/38599217-1cee1e54-3d92-11e8-9d44-e5754683689b.png)
It seems the nvm doesn't work well. Please check,
1. You've run `make deploy-v8`.
2. You have correct `lib` folder in your workspace directory.

**Comment by bitcodernull** [comment]
I remember i have done it before
i will try it again

thanks

**Comment by bitcodernull** [comment]
Thanks!
I have found the reason
i start neb as system service ,  so it can not find the lib in the workspace dir.

thanks

**Comment by royshang** [comment]
@bitcodernull  nice!
