### ISSUE TITLE
Current balance of contract

### ISSUE THREAD

**Issue by xaosaki** [nebulasio/go-nebulas#89]
Hi, can you please tell me how to get the current balance of the smart contract from the smart contract method? I already read everything I found, even tried to look at the source code, but I did not find this information.

**Comment by act262** [comment]
u should use `Call` method to get the balance for the smart contract.

**Comment by ChengOrangeJu** [comment]
Thanks @act262 : )
Issue closed

**Comment by smartpunter** [comment]
I believe, that this method is very important for developers.
You must put implimentation of this functionality on todo list, not close the issue.

requesting for accountstate is a hack, this mean that we should have something outside of blockchain, while idea is not to rely on anything outside it.

**Comment by ChengOrangeJu** [comment]
Hello @smartpunter , Thanks for your information, we will

**Comment by woniesong92** [comment]
+1 This is important

**Comment by denalimarsh** [comment]
This functionality is needed, I would like for my contract to be able get its own balance or get the balance of other addresses on-chain.

**Comment by ChengOrangeJu** [comment]
Hello @smartpunter We plan to add this function in the near future, thanks :)
