### ISSUE TITLE
Github client id and secret leftovers

### ISSUE THREAD

**Issue by eur0pa** [nebulasio/go-nebulas#92]
I was going to report this "elsewhere", but I'm not sure it pertains your scope. This set of credentials give access to GitHub as an organization and exposes data for all its members–you might want to assess whether it's a liability or not.

https://github.com/nebulasio/go-nebulas/blob/415c6ab50279aefb2ff37f447bf28a01b1e94f46/net/testing/test/main.go#L12

**Comment by ChengOrangeJu** [comment]
Hello @eur0pa , Code removed in develop branch, thanks again.
