### ISSUE TITLE
Help me understand procedure to update NAS to new status?

### ISSUE THREAD

**Issue by Glenanne** [nebulasio/go-nebulas#96]
My NAS is still on the exchange it was on when I bought it a year (+)(-) back.  I do not know if it has been changed to the New NAS Coin?  How can I tell?  I have been trying to understand for weeks---the exchange writes that they will change it but I cannot understand the directions.  PLEASE?

**Comment by ChengOrangeJu** [comment]
Hello @Glenanne Which exchange? For most exchanges, the new NAS coin is automatically changed, you don't have to do anything :)

**Comment by ChengOrangeJu** [comment]
For most exchanges, the new NAS coin is automatically changed. Github focus on technical questions.
Please move to slack channel
https://nebulasio.slack.com/messages/C71GCT953
